### ISSUE TITLE
Render helper overwrites rather than appending

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [emberjs/ember-test-helpers#1018]
The [API docs for `render`](https://github.com/emberjs/ember-test-helpers/blob/master/API.md#render) state that it "Renders the provided template and appends it to the DOM.".

To me, "appends" implies that if I call `render` multiple times within the same test, I should see each new template appended after the previous. For example if I ran this, I'd expect to see all three `<div>` elements:
 
```
it('foo', async function() {
  await render(hbs`<div id="dan-1"></div>`);
  await render(hbs`<div id="dan-2"></div>`);
  await render(hbs`<div id="dan-3"></div>`);
});
```

The reality is that I see only the output of the last call to `render`:

![image](https://user-images.githubusercontent.com/1011369/115701822-1a65d000-a360-11eb-8150-60fe3449a40d.png)

Should we be able to call `render` multiple times to append multiple templates, or am I perhaps focussing too much on the word "append"?

If overwriting is the expected behaviour, perhaps extending the sentence in the API docs to something like "Renders the provided template and appends it to the DOM, overwriting any previously-rendered template." would avoid ambiguity?

**Comment by rwjblue** [comment]
We should update the documentation, the behavior we have is _roughly_ the best we can do at the moment (without significant refactors).
