### ISSUE TITLE
Integration test with router injected into component

### ISSUE THREAD

**Issue by mmahalwy** [emberjs/ember-test-helpers#103]
I don't have the `link-to` issue but I have a component that gets router injected into it in an initializer and part of it's code is:

```
const router = this.get('router');
router.router.currentHandlerInfos.forEach(route => {
...
```

On an integration test, I keep getting `Cannot read property 'router' of undefined`. Not sure how to resolve this from an integration test standpoint or an acceptance test should be used. A good medium would be to learn how to initialize and inject router into this component

**Comment by rwjblue** [comment]
Initializers do not run for integration tests.

**Comment by mmahalwy** [comment]
@rwjblue, right, how can I inject the router into the integration test? Will using `start-app` work (although I  tried it and no luck)

**Comment by Turbo87** [comment]
You can use the new router service and inject that into the component like any other service
