### ISSUE TITLE
error thrown when running test

### ISSUE THREAD

**Issue by maverick12806** [emberjs/ember-test-helpers#1031]
I am getting an error when I run my test and I am not sure why this error is being thrown.  The error message is "_prepareOnerror should only be called once per-context".  How do I fix this error?  Thank you.

**Comment by scalvert** [comment]
Hey @maverick12806, thanks for reporting. We're going to need a bit more information in order to help you.

Could you provide a simple reproduction of this issue, or a link to the source code in order for us to debug?

**Comment by stefanpenner** [comment]
I would love to help, but without a response to @scalvert's request this isn't currently Actionable. I will be closing this, but will gladly reopen if we can get the details to dig in further and help :)
