### ISSUE TITLE
Blur event is not triggered on the current active element in the click helper

### ISSUE THREAD

**Issue by helgablazhkun** [emberjs/ember-test-helpers#1032]
**Scenario:**
Expected result: 
**GIVEN** There are two elements on the form: focusable input and label (simple div).  
**AND** Input element has focus
**WHEN** Click on the label occurs (via click test helper)
**THEN** Input gets blur event and loses its focus

Actual result: 
**Input doesn't get blur event and doesn't  lose its focus**

The root cause of the issue is that the blur event is not triggered on the current active element in the click helper in case if the clicked element is not focusable.
If the clicked element is focusable the previous active element gets blur event trough the __focus__ helper. 

**Proposed solution:** Add a call to __blur__  for the case when the clicked element is not focusable.

**Real world example:** The issue is noticed in the integration test for dropdown component with Ember Power Select in the real application. When click occurs on the dropdown option (non-focusable element) then input doesn't lose its focus in the test but it does in the real application. So Click test helper has different behaviour with browser click.

**Comment by rwjblue** [comment]
Can you create a plain HTML demo showing the real world scenario you described (e.g. codepen with just a few lines of JS wiring up a blur event)?

I want to make sure that we properly emulate the events across all of our supported browsers.

**Comment by helgablazhkun** [comment]
Please use this example: https://codepen.io/helgablazhkun/pen/qBrjbzd
Events are logged into the console.

**Comment by helgablazhkun** [comment]
Closed 
https://github.com/emberjs/ember-test-helpers/pull/1033
