### ISSUE TITLE
EmberApplicationInstance willDestroy in settled.ts uses the wrong `internalPendingRequests`

### ISSUE THREAD

**Issue by raycohen** [emberjs/ember-test-helpers#1172]
upon updating ember-test-helpers, I have test code that resets the app hit the app instance `willDestroy` method, which errors on `internalPendingRequests.clearPendingRequests()` because `internalPendingRequests` is the (nonzero) integer result of calling the `pendingRequests` method.

Here's where the pendingRequests method is chained on the require that prevents accessing the other methods:
https://github.com/emberjs/ember-test-helpers/blob/9c6e884d8572e7c262e4915d88dd61df787deda9/addon-test-support/%40ember/test-helpers/settled.ts#L30-L31

error occurs here:
https://github.com/emberjs/ember-test-helpers/blob/9c6e884d8572e7c262e4915d88dd61df787deda9/addon-test-support/%40ember/test-helpers/settled.ts#L59

likewise the `off` calls are passing `undefined` since `internalPendingRequests` is an integer and not a module

If you look at the deleted code in https://github.com/emberjs/ember-test-helpers/pull/1047 it was not chaining `pendingRequests` on the old `require('ember-testing/lib/test/pending_requests')` which allowed accessing the different methods from that module.

Is a PR welcome here?

**Comment by ginomiglio** [comment]
Would it be possible to cut a release that includes this change?
