### ISSUE TITLE
Await visit helper waits for ember runloop later code

### ISSUE THREAD

**Issue by colenso** [emberjs/ember-test-helpers#1174]
I was trying to get started with acceptance testing in our app and had a case where I was setting a flag after 60 seconds. But for some reason the code `await visit('/login')` waits for the `later` code to execute.
Here's my sample app:
https://github.com/colenso/test-app

It's pretty simple:
app/controllers/login.js has the code that sets the flag
```
import Controller from '@ember/controller';
import { later } from '@ember/runloop';
import { tracked } from '@glimmer/tracking';
import { action } from '@ember/object';

export default class LoginController extends Controller {

  @tracked
  isReady = false

  @action
  setIsReady() {
    later(() => {
      this.isReady = true;
    }, 60000)
  }
}

```

app/templates/login.hbs has the code that calls the function
```
{{page-title "Login"}}
<div
  {{did-insert this.setIsReady}}
>
  {{log this.isReady}}
  {{#if this.isReady}}
    Page is ready now
  {{/if}}
</div>

{{outlet}}
```

And tests/acceptance/login-test.js has the test code that I got following the guides for writing acceptance tests https://guides.emberjs.com/release/testing/testing-application/
```
import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';

module('Acceptance | login', function (hooks) {
  setupApplicationTest(hooks);

  test('visiting /login', async function (assert) {
    await visit('/login');

    assert.equal(currentURL(), '/login');
  });
});

```

The test times out at 60 seconds because for some weird reason it's waiting for the later code to execute.

**Comment by colenso** [comment]
@rwjblue Any idea on what this is about? Or how I can get around this?

**Comment by frykten** [comment]
It (the [visit helper](https://github.com/emberjs/ember-test-helpers/blob/master/API.md#visit)) waits for the page to be "settled", if I understand well the API Documentation, which kind of makes sense (you usually wanna wait for the whole page to be loaded and finished). For info on the "settled" keyword, [lookithere](https://github.com/emberjs/ember-test-helpers/blob/master/API.md#issettled).

Maybe what you're looking for in this particular issue is more like a `waitFor(HeaderSelector)` (cf. [link](https://github.com/emberjs/ember-test-helpers/blob/master/API.md#waitfor)).

**Comment by colenso** [comment]
Thanks @frykten this is exactly the behavior that I was experiencing. Since this is not a bug, I'm going to close this issue now.
