### ISSUE TITLE
Check for "maxlength" attribute instead of "maxLength" in "-guard-for-maxlength.ts"

### ISSUE THREAD

**Issue by shubham88fru** [emberjs/ember-test-helpers#1202]
https://github.com/emberjs/ember-test-helpers/blob/7d0aab9909102f00f985f451bece96a1cfc74d8b/addon-test-support/%40ember/test-helpers/dom/-guard-for-maxlength.ts#L22

Hi All,

Shouldn't this piece of code above be doing - 
```js
element.getAttribute('maxlength')
```
(i.e. lowercase 'maxlength').
instead of camelCase 'maxLength' ?

If understand correctly,``` element ``` represents the DOM element, and if I refer MDN the maximum length attribute is
``` maxlength ``` and **not**  ``` maxLength```

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength

**Comment by rwjblue** [comment]
We can make that change, but it shouldn't make a difference since `el.getAttribute` calls `.toLowerCase()` before actually doing any work ([MDN docs here](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute#lower_casing)).

**Comment by shubham88fru** [comment]
> We can make that change, but it shouldn't make a difference since `el.getAttribute` calls `.toLowerCase()` before actually doing any work ([MDN docs here](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute#lower_casing)).

Ohh I see. Cool. Thanks!

**Comment by rwjblue** [comment]
Going to close this for now, happy for someone to send a PR though.
