### ISSUE TITLE
Support for finding elements by text, label, alt text, etc.?

### ISSUE THREAD

**Issue by tstormk** [emberjs/ember-test-helpers#1244]
Are there any plans to support finding elements by attributes such as text, label, alt text, etc., similar to [Testing Library queries](https://testing-library.com/docs/queries/about)? I think this would be valuable to provide as an alternative to just finding elements by CSS selectors.

We could add functions `findByText`, `findByLabelText`, `findByAltText`, and so on.

**Comment by bertdeblock** [comment]
I would opt for not having Ember-specific utils for this, and suggest that people use the Testing Library utils directly for querying the DOM. It has been working very well for us.

**Comment by NullVoxPopuli** [comment]
Gonna close as there is nothing stopping folks from using `@testing-library/dom`
