### ISSUE TITLE
ember-try embroider-safe fails on CI

### ISSUE THREAD

**Issue by geneukum** [emberjs/ember-test-helpers#1261]
In config/ember-try.js, we try to pull a version of @embroider/test-setup that matches the latest version of the @embroider/core package. 

Unfortunately, it seems like these packages were not updated in lockstep (https://www.npmjs.com/package/@embroider/test-setup is at 1.8.3 where https://www.npmjs.com/package/@embroider/core is at 1.9.0).

Should we update the ember-try.js config such that this is not the case?

**Comment by chriskrycho** [comment]
Fixed by just bumping the lockfile in #1280.

**Comment by chriskrycho** [comment]
(The extra work described here may also be fine, but it's no longer causing CI issues!)
