### ISSUE TITLE
Convert to TS or supply ambient definitions

### ISSUE THREAD

**Issue by chriskrycho** [emberjs/ember-test-helpers#1268]
As part of [Ember.js RFC #0800](https://rfcs.emberjs.com/id/0800-ts-adoption-plan), this package needs to supply type definitions. Preferably, this would happen by converting to TS and generating from the source; as an alternative, it can publish ambient types (presumably starting with the ones on DefinitelyTyped).

All the members of the Typed Ember team are happy to advise on how to do this; feel free to reach out [in #dev-typescript on Discord][discord] if you have questions!

[discord]: https://discord.com/channels/480462759797063690/786312479620726804

**Comment by gitKrystan** [comment]
I am taking a stab at this. 👍

It should help us resolve https://github.com/emberjs/ember.js/issues/20254 as well.

**Comment by gitKrystan** [comment]
Done https://github.com/emberjs/ember-test-helpers/pull/1234 :-P

**Comment by chriskrycho** [comment]
Ha! I forgot about that. Also, what a great PR number that was!

**Comment by chriskrycho** [comment]
Talking with @gitKrystan in Discord: she's going to try to get this switched over to using the Ember preview types, and then we'll see about getting a release cut.
