### ISSUE TITLE
Property 'element' does not exist on type 'TestContext'. ?

### ISSUE THREAD

**Issue by oliverlj** [emberjs/ember-test-helpers#1307]
```
error TS2339: Property 'element' does not exist on type 'TestContext'.

18     const textContent = this.element.textContent ?? '';
```

it was here https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fdf57eeb380d06e01fb3cf14d38b223940232f1d/types/ember-test-helpers/index.d.ts#L65

**Comment by DanMonroe** [comment]
Oliver, see https://github.com/emberjs/ember-test-helpers/issues/1306

**Comment by oliverlj** [comment]
Thanks you ! i will watch the migration with ember qunit 6.1
