### ISSUE TITLE
Upgrade `registerHook` and `runHooks` as official public APIs

### ISSUE THREAD

**Issue by drewlee** [emberjs/ember-test-helpers#1341]
The [helper hooks API](https://github.com/emberjs/ember-test-helpers/blob/v2.9.3/addon-test-support/@ember/test-helpers/-internal/helper-hooks.ts) was initially implemented in a "semi-private" fashion as part of a pilot. However, it's been in use for several years now and has proven to be quite useful (leveraged by [ember-a11y-testing](https://github.com/ember-a11y/ember-a11y-testing)) and stable. This warrants exporting them as official public APIs in `@ember/test-helpers`. It would also allow for exposing the TypeScript types associated with the helper hooks.

CC @scalvert and @rwjblue for awareness.

**Comment by drewlee** [comment]
I can put up a PR for this if there are no major objections.

**Comment by chriskrycho** [comment]
Please do! I think we are broadly aligned that this is good.

**Comment by scalvert** [comment]
Thanks, @drewlee! Much appreciated!

**Comment by drewlee** [comment]
Addressed via PR #1344

**Comment by NullVoxPopuli** [comment]
These are now documented in API.md!
