### ISSUE TITLE
How to extend ember-test-helpers?

### ISSUE THREAD

**Issue by ming-codes** [emberjs/ember-test-helpers#137]
If an Ember CLI Addon wants to offer test helpers in a way that's framework agnostic, it would make sense to build those test helpers by extending `ember-test-helpers`.

Does `ember-test-helpers` offer ways to extend it? If so, can a guide be written to show how to do it?

Specifically, I'm looking to attach additional methods to `test-module-for-component#callbacks` and `test-module-for-model#callbacks`.

**Comment by ming-codes** [comment]
Circling back on this one. Any help would be appreciated.

**Comment by Turbo87** [comment]
@ming-codes have a look at ember-native-dom-helpers that do something similar to what you're asking for
