### ISSUE TITLE
Remove old compatibility code

### ISSUE THREAD

**Issue by Windvis** [emberjs/ember-test-helpers#1433]
It seems the addon still contains code for very old (Ember Data) addon compatibility:

For example: https://github.com/emberjs/ember-test-helpers/blob/dd7bd457f6e440ea263827a4b6320b9ae797a0e5/addon/addon-test-support/%40ember/test-helpers/-internal/build-registry.ts#L150-L158

I verified in the [Discord](https://discord.com/channels/480462759797063690/480501977931972608/1138945168666538005) and this code should no longer be needed.

A benefit of removing this code is that it still uses `loader.js` code directly, which is up for removal: https://github.com/emberjs/rfcs/pull/938

**Comment by NullVoxPopuli** [comment]
This will be removed in the next major!
