### ISSUE TITLE
New app failing to start

### ISSUE THREAD

**Issue by myasonik** [emberjs/ember-test-helpers#1447]
Creating a new app with `ember new Gencon-Buddy --lang en` then `cd Gencon-Buddy` then `npm start` fails with: 
```
Build Error (broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers]) in @ember/test-helpers/-internal/is-promise.js

ENOENT: no such file or directory, open '/tmp/broccoli-177672Xec01zXvjoI/out-011-broccoli_persistent_filter_babel_babel_ember_test_helpe/@ember/test-helpers/-internal/is-promise.js'
```

<details>
<summary>Full report</summary>
<pre><code>
=================================================================================

ENV Summary:

  TIME: Sun Dec 10 2023 21:54:21 GMT-0500 (Eastern Standard Time)
  TITLE: ember
  ARGV:
  - /home/myasonik/.nvm/versions/node/v21.3.0/bin/node
  - /home/myasonik/Workspace/Gencon-Buddy/node_modules/.bin/ember
  - serve
  EXEC_PATH: /home/myasonik/.nvm/versions/node/v21.3.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/myasonik/Workspace/Gencon-Buddy/node_modules/.bin
  - /home/myasonik/Workspace/node_modules/.bin
  - /home/myasonik/node_modules/.bin
  - /home/node_modules/.bin
  - /node_modules/.bin
  - /home/myasonik/.nvm/versions/node/v21.3.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin
  - /home/myasonik/.nvm/versions/node/v21.3.0/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /snap/bin
  PLATFORM: linux x64
  FREEMEM: 61372518400
  TOTALMEM: 67194347520
  UPTIME: 16309.05
  LOADAVG: 1.55,0.72,0.52
  CPUS:
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3797
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3665
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3754
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3754
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3754
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3663
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3754
  - 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz - 3754
  ENDIANNESS: LE
  VERSIONS:
  - acorn: 8.11.2
  - ada: 2.7.4
  - ares: 1.20.1
  - base64: 0.5.1
  - brotli: 1.0.9
  - cjs_module_lexer: 1.2.2
  - cldr: 44.0
  - icu: 74.1
  - llhttp: 9.1.3
  - modules: 120
  - napi: 9
  - nghttp2: 1.58.0
  - nghttp3: 0.7.0
  - ngtcp2: 0.8.1
  - node: 21.3.0
  - openssl: 3.0.12+quic
  - simdutf: 4.0.4
  - tz: 2023c
  - undici: 5.27.2
  - unicode: 15.1
  - uv: 1.46.0
  - uvwasi: 0.0.19
  - v8: 11.8.172.17-node.17
  - zlib: 1.2.13.1-motley-5daffc7

ERROR Summary:

  - broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open '/tmp/broccoli-177672Xec01zXvjoI/out-011-broccoli_persistent_filter_babel_babel_ember_test_helpe/@ember/test-helpers/-internal/is-promise.js'
    at Object.writeFileSync (node:fs:2352:20)
    at /home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/broccoli-persistent-filter/index.js:483:10
    at tryCatcher (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:498:33)
    at publish (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:484:9)
    at flush (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
  - code: [undefined]
  - codeFrame: ENOENT: no such file or directory, open '/tmp/broccoli-177672Xec01zXvjoI/out-011-broccoli_persistent_filter_babel_babel_ember_test_helpe/@ember/test-helpers/-internal/is-promise.js'
  - errorMessage: @ember/test-helpers/-internal/is-promise.js: ENOENT: no such file or directory, open '/tmp/broccoli-177672Xec01zXvjoI/out-011-broccoli_persistent_filter_babel_babel_ember_test_helpe/@ember/test-helpers/-internal/is-promise.js'
        in /home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/addon-test-support
        at broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers] (Babel: @ember/test-helpers)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: @ember/test-helpers/-internal/is-promise.js
    - line: [undefined]
    - treeDir: /home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/addon-test-support
  - message: @ember/test-helpers/-internal/is-promise.js: ENOENT: no such file or directory, open '/tmp/broccoli-177672Xec01zXvjoI/out-011-broccoli_persistent_filter_babel_babel_ember_test_helpe/@ember/test-helpers/-internal/is-promise.js'
        in /home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/addon-test-support
        at broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers] (Babel: @ember/test-helpers)
  - name: Error
  - nodeAnnotation: Babel: @ember/test-helpers
  - nodeName: broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers]
  - originalErrorMessage: ENOENT: no such file or directory, open '/tmp/broccoli-177672Xec01zXvjoI/out-011-broccoli_persistent_filter_babel_babel_ember_test_helpe/@ember/test-helpers/-internal/is-promise.js'
  - stack: Error: ENOENT: no such file or directory, open '/tmp/broccoli-177672Xec01zXvjoI/out-011-broccoli_persistent_filter_babel_babel_ember_test_helpe/@ember/test-helpers/-internal/is-promise.js'
    at Object.writeFileSync (node:fs:2352:20)
    at /home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/broccoli-persistent-filter/index.js:483:10
    at tryCatcher (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:326:21)
    at invokeCallback (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:498:33)
    at publish (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:484:9)
    at flush (/home/myasonik/Workspace/Gencon-Buddy/node_modules/@ember/test-helpers/node_modules/rsvp/dist/rsvp.js:2441:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

=================================================================================
</code></pre>
</details>

**Comment by NullVoxPopuli** [comment]
is your node version the latest for 21.x?

Does this issue occur on latest node@20.x?

**Comment by myasonik** [comment]
I was on 21.3, didn't realize that 21.4 had come out. Upgrading resolved the issue.

Thanks!
