### ISSUE TITLE
Update to ember-cli-babel@8+ to fix a json5 vulnerability

### ISSUE THREAD

**Issue by Z-Zhao** [emberjs/ember-test-helpers#1448]
Latest version has dependency on json5@0.5.1 which is high Severity reported by "npm audit"
json5  <1.0.2
Severity: high
Prototype Pollution in JSON5 via Parse Method - https://github.com/advisories/GHSA-9c47-m6qq-7p4h

Below is the result of "npm list json5"
├─┬ @ember/test-helpers@3.3.0
│ └─┬ ember-cli-babel@7.26.11
│   └─┬ babel-plugin-module-resolver@3.2.0
│     └─┬ find-babel-config@1.2.0
│       └── json5@0.5.1

you should update to ember-cli-babel@^8.0.0 which includes the below change
 [https://github.com/emberjs/ember-cli-babel/pull/492](url)

**Comment by Z-Zhao** [comment]
https://github.com/emberjs/ember-test-helpers/blob/9cec68dc6aa9c0a7a449eb89797eb81299fa727f/addon/package.json#L55

**Comment by NullVoxPopuli** [comment]
want to submit a PR?

**Comment by NullVoxPopuli** [comment]
This was resolved in https://github.com/emberjs/ember-test-helpers/releases/tag/v3.3.1-%40ember%2Ftest-helpers
