### ISSUE TITLE
initializers affect component integration tests if there is an acceptance test

### ISSUE THREAD

**Issue by jelhan** [emberjs/ember-test-helpers#146]
If there is an acceptance test an initalizers and instance-initializers affects component integration tests. If not they won't. Inconsistent errors depending on test filters is the result. Really confusing...

Let my give an example: I have an initalizer to configure webshim polyfill. I have a component integration test which was affected by webshim. Tests passes running `ember test -m "Integration | Component | webshim affected component"` while failing on `ember test` (which also runs some acceptance tests).

Was even more confusing since tests passed in chrome (which has native support for the feature) but failed in phantomjs (which uses polyfill) but ember isn't responsible therefore. :smile:

ember-cli: 1.13.13
ember-qunit: 0.4.16

_Moved from https://github.com/ember-cli/ember-cli/issues/5405 as suggested._

**Comment by Turbo87** [comment]
The only possible solution that I see for this is starting a new browser instance for every single test, which is obviously very slow. Integration test should in general not rely on any initializers. You could use ember-exam to randomize the test order and detect issues like that.
