### ISSUE TITLE
Conflicting rule in `"resolutions"` in root `package.json` and addon's `package.json` for `rimraf` causing failure.

### ISSUE THREAD

**Issue by shubham88fru** [emberjs/ember-test-helpers#1463]
Hi,

I cloned the master branch and tried doing `yarn install` and then `yarn test` but seeing the following error - 
<img width="1332" alt="Screenshot 2024-07-22 at 2 58 08 PM" src="https://github.com/user-attachments/assets/c0fa9d05-47c7-4d02-841c-21a3bb7342bd">

This seems to be happening because the `addon` required `rimraf` version `^5.0.1` - 
https://github.com/emberjs/ember-test-helpers/blob/3b83f12656ab9443603da79575ab8a744d56fcb9/addon/package.json#L104

but the `"resolutions"` in the root `package.json` restricts `rimraf` version to `< 5.0.0` -
https://github.com/emberjs/ember-test-helpers/blob/3b83f12656ab9443603da79575ab8a744d56fcb9/package.json#L17

because of this, on doing `yarn install` a lower version of `rimraf` (version 4.x) is installed, than what is need for the addon module (version 5.x) - 
<img width="685" alt="Screenshot 2024-07-22 at 3 04 32 PM" src="https://github.com/user-attachments/assets/ccc3888b-65e2-4bf1-bd40-fd1d5d3213cc">

I tried removing the `rimraf` entry from `"resolutions"` altogether and was able to run the tests.

Please let me know your thoughts on this. Should I create a PR for this?

**Comment by NullVoxPopuli** [comment]
This is solved by this PR: https://github.com/emberjs/ember-test-helpers/pull/1453
waiting for review over there.

**Comment by shubham88fru** [comment]
Closing this issue since PR #1453 has been merged.
