### ISSUE TITLE
Typescript compilation errors importing types from `dom-element-descriptors`

### ISSUE THREAD

**Issue by syphe** [emberjs/ember-test-helpers#1500]
We are having issues with ember-test-helpers while trying to compile our project.

It relates to any imports from `dom-element-descriptors`.

The error we receive is:

`The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("dom-element-descriptors")' call instead.`

I have mitigated this error in our project by patching `//@ ts-expect-error` above each error instance in the package, but this is obviously not idea.

For context, our tsconfig extends `@tsconfig/ember/tsconfig.json` and `module=NodeNext`, `moduleResolution=NodeNext`

**Comment by NullVoxPopuli** [comment]
NodeNext can't be used without type=module - because we use imports -- so you'll want to remove those specified options

**Comment by syphe** [comment]
Thanks @NullVoxPopuli I ended up dropping those properties from the config, and just relying on the ember base tsconfig to provide the spec for it. I guess for the ember base config to be set to NodeNext will require this package to be type=module
