### ISSUE TITLE
Release v0.6.0

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#192]
Since we haven't heard any complaints or experienced any problems with the removal of Klassy it might be time to take v0.6.0 out of beta and officially release it.

@rwjblue @trentmwillis opinions?

**Comment by rwjblue** [comment]
👍 from me...

**Comment by trentmwillis** [comment]
Sounds good to me!

**Comment by Turbo87** [comment]
resolved by https://github.com/emberjs/ember-test-helpers/commit/a91804c8e3d652f818e2b7f84efbf3eb43ca60d7
