### ISSUE TITLE
Allowing rejected promises in integration tests

### ISSUE THREAD

**Issue by amk221** [emberjs/ember-test-helpers#197]
How can one test a Promise Proxy Object? (Because they always re-throw)
* [Example twiddle failing test](https://ember-twiddle.com/#/42f680ffe9f245a76c4e87564c36cdec?openFiles=tests.integration.components.my-component-test.js%2C)
* [Example twiddle failing test with Ember Data](https://ember-twiddle.com/57beea373178e4f1e45c2bf473f233b1?openFiles=tests.integration.components.my-component-test.js%2C)

_([Related issue](https://github.com/emberjs/ember.js/issues/11469) closed jan 2016)_

**Comment by rwjblue** [comment]
This seems related to https://github.com/emberjs/ember.js/issues/15569, right?

I'm closing for now (see detailed explanation in https://github.com/emberjs/ember.js/issues/15569#issuecomment-347608122), but happy to reopen if I have made a mistake.
