### ISSUE TITLE
Way to use extended EventDispatcher

### ISSUE THREAD

**Issue by kbullaughey** [emberjs/ember-test-helpers#20]
I'm looking at using the [ember-mobiletouch](https://github.com/runspired/ember-mobiletouch) addon, which extends `Ember.EventDispatcher`. However, I don't see a way to get this to work with Ember unit component testing. It seems that the `setupComponent` method of `test-module-for-component` assumes the dispatcher will be a stock `Ember.EventDispatcher`. Is there a natural way to configure the dispatcher? Perhaps an overridable hook which defaults to the stock dispatcher? Alternatively, we could modify `ember-mobiletouch` to reopen the dispatcher instead of extend it. Thoughts?

**Comment by Turbo87** [comment]
@kbullaughey I'm in the process of cleaning up the issues in this repo. Is this one still relevant?

**Comment by rwjblue** [comment]
Ya, very recent PR I merged by @cibernox (into 0.7.0 prereleases) supports having a custom event dispatcher.
