### ISSUE TITLE
contextualizeCallbacks prevents custom test instance helpers

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember-test-helpers#204]
I want to write instance-level helper methods on a test class like so:
```js
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';
import { moduleForComponent, test } from 'ember-qunit';
const { run } = Ember;
let services;

moduleForComponent('service-authorizations', 'Integration: component:service-authorizations', {
  integration: true,

  fooBar(name) {
    return this.$(`.foo:contains(${name}) .bar`);
  },

  beforeEach() {
    this.render(hbs`{{foo-bar 1}} {{foo-bar 2}} {{foo-bar 3}}`);
  }
});

test('foo bars', function(assert) {
  assert.equal(this.fooBar(1).is(':disabled'), true);
  assert.equal(this.fooBar(2).is(':disabled'), false);
  assert.equal(this.fooBar(3).is(':disabled'), false);
});
```

`contextualizeCallbacks` memoizes anything I add in the `moduleForComponent` block and ignores arguments, so `this.fooBar(2)` returns the result from `this.fooBar(1)`.

**Comment by jamesarosen** [comment]
I can solve this by adding the methods in the `beforeEach` block instead of on the "prototype" object. It's just messier.

**Comment by Turbo87** [comment]
Is functions on the objects being converted to methods on the context object officially supported API of this project?

**Comment by jamesarosen** [comment]
> Is functions on the objects being converted to methods on the context object officially supported API of this project?

Perhaps not. It seemed like an obvious thing to do to me.

**Comment by rwjblue** [comment]
Yeah, this is a major gotcha of the memoization system.  The next iteration (from emberjs/rfcs#232) will not include this type of memoization.

I'm going to close this for now (since there really isn't much we can do about it in the current API)...
