### ISSUE TITLE
Simplify support matrix.

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember-test-helpers#206]
I just found that this addon has **a lot** of test scenarios:

- ember-1.10
- ember-1.11
- ember-1.12
- ember-1.13
- ember-2.0
- ember-2.1
- ember-2.2
- ember-2.3
- ember-2.4
- ember-2.5
- ember-2.6
- ember-release
- ember-beta
- ember-canary
- ember-alpha
- ember-data-2.3

Can we simplify that a bit?
I think that at least 1.10, 1.11 and 1.12 should go. Is `alpha` still a thing? When should 1.13 die?

If you agree I can give it a try. If anyone is aware of any code just to support some of the scenarios being removed please tell.

**Comment by rwjblue** [comment]
This project has lots of scenarios because we currently support all of those ember versions, if we intend to support them we should test them. 

I'm happy to start having the discussion of dropping support for non-LTS and non-current releases, but we'd need to make that a 0.7.0 I believe.

**Comment by cibernox** [comment]
That sounds perfect. At least dropping support for 1.X seems reasonable at this point. 
The last 2 LTS releases seems reasonable policy to me, and that will soon be 2.8 and 2.12

**Comment by Turbo87** [comment]
this was addressed by https://github.com/emberjs/ember-test-helpers/pull/213
