### ISSUE TITLE
Convert to Ember addon

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#210]
right now the integration of this package into ember-qunit and ember-mocha is a little messy. IMHO we should convert this into a real addon to make the build code less complex and error prone.

/cc @rwjblue @trentmwillis

**Comment by trentmwillis** [comment]
Totally agree. I think it also would lower the barrier for new contributors.

**Comment by Turbo87** [comment]
resolved by https://github.com/emberjs/ember-test-helpers/pull/213
