### ISSUE TITLE
New `setupRenderingTest` seems to recreate the `#ember-testing-container` for every test

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember-test-helpers#228]
Run the tests of an app with several tests. P.e. this branch of `ember-basic-dropdown`: https://github.com/cibernox/ember-basic-dropdown/pull/349

Check the dom after the suite has finished: 
<img width="897" alt="screen shot 2017-10-19 at 01 01 32" src="https://user-images.githubusercontent.com/265339/31768713-e1ad7b5e-b4d0-11e7-932b-d9c26e52af96.png">

**Comment by rwjblue** [comment]
Thank you for reporting!  I'm fairly certain that I have made a silly mistake in https://github.com/emberjs/ember-test-helpers/pull/226.  I'll try to dig in to confirm and fix today...

**Comment by rwjblue** [comment]
Should be fixed by https://github.com/emberjs/ember-test-helpers/pull/229. I'll land and release once someone has had a chance to do a sanity check review...

**Comment by cibernox** [comment]
I can confirm that it is fixed now 🎉
