### ISSUE TITLE
TypeError: Cannot read property 'resolveRegistration' of undefined

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#230]
With the new testing APIs I'm hitting this error for a lot of our tests:

```
TypeError: Cannot read property 'resolveRegistration' of undefined
     at exports.default (http://localhost:3201/assets/vendor.js:115071:34)
     at exports.default (http://localhost:3201/assets/vendor.js:115145:32)
     at Object.<anonymous> (http://localhost:3201/assets/tests.js:56620:44)
     at callHook (http://localhost:3201/assets/test-support.js:3910:25)
     at runHook (http://localhost:3201/assets/test-support.js:3933:7)
     at Object.advance (http://localhost:3201/assets/test-support.js:3536:26)
     at begin (http://localhost:3201/assets/test-support.js:5348:20)
     at http://localhost:3201/assets/test-support.js:5308:6
```

which seems to be caused by https://github.com/danielspaniel/ember-data-factory-guy/blob/958a51632e1252e9af949148759f91c13ab77293/addon/utils/load-scenarios.js#L16

/cc @danielspaniel

**Comment by rwjblue** [comment]
@Turbo87 - What ember version? What type of test (`setupTest` or `setupRenderingTest`)? What are you passing in to `loadScenarios`?

**Comment by Turbo87** [comment]
> What ember version?

Ember 2.12

> What type of test (setupTest or setupRenderingTest)?

`setupTest()` in this case

> What are you passing in to loadScenarios?

We have been calling `manualSetup(this.container)` so far, which essentially does `this.container.owner.resolveRegistration(...)`. I'm now passing `this.owner` instead, but `this.owner.owner` does not exist so the call above fails.

I've submitted https://github.com/danielspaniel/ember-data-factory-guy/pull/308 to make the addon compatible with our efforts here. 

I guess this is not actually a bug in the new API implementation, just an addon that is not yet compatible.

**Comment by rwjblue** [comment]
Ahh, gotcha.  Thanks for tracking it down!

**Comment by danielspaniel** [comment]
https://github.com/danielspaniel/ember-data-factory-guy/releases/tag/v2.13.8  has the fix for this issue in factory-guy

**Comment by Turbo87** [comment]
@danielspaniel thanks!
