### ISSUE TITLE
Broken tests in v0.7.0-beta.8

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#231]
It looks like `v0.7.0-beta.8` (with https://github.com/emberjs/ember-test-helpers/pull/229) broke some of our existing old API tests.

Most failures seem to look like this:

```
        actual: >
            Element .edit-order-email-dialog does not exist
        expected: >
            Element .edit-order-email-dialog exists
```

**Comment by rwjblue** [comment]
What kind of test (moduleForComponent, etc)? Are all failing or just some? If you inspect the DOM at the time of the failed assertion does it contain the correct things (but just in a nested element or something)?

**Comment by Turbo87** [comment]
This was apparently caused by `qunit-dom` caching the reference to the `#ember-testing` element, but #229 changed the behavior to recreate a new element for each test. This issue was resolved in https://github.com/simplabs/qunit-dom/pull/33.
