### ISSUE TITLE
Rename to `@ember/test-helpers`

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#240]
With the introduction of RFC 176 Ember moved towards import paths prefixed with `@ember/` which ultimately should use the `@ember` scope on npm. This gives us a better indicator of a project being official or a community-project. Since `ember-test-helpers` is an official project it might make sense to move it to `@ember/test-helpers` too.

https://github.com/emberjs/rfcs/pull/268 is introducing a public API for this package for the first time so we should probably decide this until the RFC lands.

/cc @rwjblue

**Comment by rwjblue** [comment]
👍 I am in favor of this. Since this package is generally provided as a transitive dependency, the only _real_ issue would be to ensure that the current `ember-test-helpers` imports continue to work after the transition (which should be pretty easy).
