### ISSUE TITLE
Add "owner" reserved word warning

### ISSUE THREAD

**Issue by jrowlingson** [emberjs/ember-test-helpers#244]
After running [`ember-qunit-codemod`](https://github.com/rwjblue/ember-qunit-codemod) against our app I observed that a test was falling with the following message:

`TypeError: Cannot read property 'apply' of undefined`

The relevant potion of the affected test:

```
  test('it displays the project owner', async function(assert) {
    this.set('owner', 'some_username');
    await render(hbs`{{project owner=owner}}`);
    
    ...
    
  });
```

It looks like this is now falling because the `owner` property is now set within the test context (https://github.com/emberjs/ember-test-helpers/blame/0cacde9a1ba308409394b18f3705e60499955b45/addon-test-support/%40ember/test-helpers/setup-context.js#L90
).

I am not sure what may be the best way to handle this, but, I am thinking adding a check prior to setting `owner` may be helpful.

**Comment by Turbo87** [comment]
That seems like a good idea. We should probably warn whenever someone tries to set `owner`, `element` or any of the other keywords.

Or we make `this.get/set()` operate on a different context, though that might be confusing 🤔

**Comment by rwjblue** [comment]
Yep, totally happy with this. But not quite sure how to implement. I suppose we could swap from normal property sets to Object.defineProperty with a setter that throws a helpful error?

**Comment by Turbo87** [comment]
can't we do that check in the `.set()` function that we put onto `this`?

**Comment by rwjblue** [comment]
Sure, but won’t catch most cases. I don’t think most folks go through set unless required...
