### ISSUE TITLE
Speed up settled()

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#260]
It seems that each call to `await settled()` is unnecessarily slowing down the test runs since it will *always* wait at least 10ms before resolving. I'd like to propose some sort of exponential backoff for the timer interval that starts with 0ms, then 1ms, 2ms, 5ms, 10ms, 10ms, 10ms, or something like that.

For a test suite of 1000 async tests using about 5 async test helpers each this amounts to 50000ms that might potentially be wasted so this is actually a huge deal 🤔

**Comment by rwjblue** [comment]
Sounds good to me...
