### ISSUE TITLE
Update `fireEvent` to use `KeyboardEvent` and `MouseEvent` constructors.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#266]
From https://github.com/emberjs/ember-test-helpers/pull/258#discussion_r155955704.

> IDK if this targets Ember 3.0, but if it does, then we don't need this as the MouseEvent constructor works in IE11+. Probably the same will happen to KeyboardEvent

`@ember/test-helpers` does still support running on older browsers (it should support the full spectrum of browsers that the supported Ember versions support), which means that we will have to support IE9 and IE10 until we drop support for testing Ember 2.x (which will be quite a long time). However, we can try to detect that a given browser supports `new MouseEvent()` or `new KeyboardEvent()` and use the newer syntax whenever possible.

**Comment by cibernox** [comment]
I'll try to do this now

**Comment by ggayowsky** [comment]
Since fireEvent does not use the MouseEvent constructor (and instead uses event.initMouseEvent), there is no way to pass the movementX or movementY parameters to a `mousemove` event.

**Comment by rwjblue** [comment]
Yep, this is definitely still something we need to do. I just don’t think anyone has had a chance to get to it.

We love PR’s 😃

**Comment by ggayowsky** [comment]
I am working on it now.

**Comment by rwjblue** [comment]
We still support IE9/IE10 (this library definitely still supports Ember 2.x), so we will need to fallback to the existing solution for those browsers.
