### ISSUE TITLE
Add `find` and `findAll` helpers.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#278]
I'd like to add `find` and `findAll` to make it easy to swap `ember-native-dom-helpers` with `@ember/test-helpers`, but have `find` and `findAll` as deprecated...

I do not think this is "how we teach" folks, but this will make migration from much easier...

**Comment by Turbo87** [comment]
what is the alternative API if you're not using `find/findAll`?

**Comment by rwjblue** [comment]
Hmm, I'm confused. The API proposed (and merged) is to just "use the dom" via `this.element.querySelector` or `this.element.querySelectorAll`...

**Comment by rwjblue** [comment]
FWIW, I _think_ that this will be somewhat less common (especially with `qunit-dom`). Almost all of the `find` usage in the various (fairly large) apps that I reviewed are things like `assert.equal(find('.some-thing').length, 2)` (where the `find` is _only_ used for an assertion).

**Comment by Turbo87** [comment]
yeah, I think if we officially recommend `qunit-dom` as an alternative then this will be fine. for the few other cases where more complex assertions are needed we can still use `this.element` directly.

**Comment by nlfurniss** [comment]
> where more complex assertions are needed we can still use this.element directly.

Having to deal with NodeLists is a major PIA; having something like `assert.dom('.class).each(...)` would be a lot cleaner

**Comment by snewcomer** [comment]
@Turbo87 @rwjblue Any further thoughts on this?  I guess from a refactor standpoint, having these methods available would be :ok_hand:
