### ISSUE TITLE
Unsafe options usage in isSettled

### ISSUE THREAD

**Issue by Frozenfire92** [emberjs/ember-test-helpers#283]
This is definitely a fault on my end, but something I think is worth bringing up, at least for anyone else who may encounter this.

We have been using the library for years, however a few of our tests were using it incorrectly. This wasn't a problem in the past as it was a bit safer.

Typical usage
```
import wait from 'ember-test-helpers/wait';
...
return wait().then(()=>{
    assert....
})
```

Which is correct usage, however a few of my tests used it incorrectly, for example `wait(3000)` thinking it would also wait 3 seconds. This wasn't a problem in the past as the code in question used `hasOwnProperty` which was safe on a variable which was a number. Now it uses the `in` keyword which breaks on non objects.

We would see errors such as `Uncaught TypeError: Cannot use 'in' operator to search for 'waitForTimers' in 500`

[how it was](https://github.com/emberjs/ember-test-helpers/blob/v0-6-x/lib/ember-test-helpers/wait.js#L55-L57)
[how it is now](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/settled.js#L112-L116)

Easiest fix for users: remove the number, and better understand how/what wait is actually doing
Easiest fix for library: explicity check options is an object, and not just undefined

**Comment by rwjblue** [comment]
Thanks for reporting!  I think the best fix is probably to have an assertion with a helpful error message.  I'm thinking of something like the following (before the various `in` check that are done now):

```js
import { assert} from '@ember/debug';

// ...snip...
assert(`The 'settled' (formerly 'wait') testing helper only accepts 'undefined' or an object. You passed ${options}`, typeof options === 'object' && options !== null);
```

It should be a straightforward patch if you have the time?
