### ISSUE TITLE
Create public API for accessing the root element. 

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#284]
This would essentially be the string argument case of `-get-element`, but allows other third party DOM helpers to function without needing the `this` context of the test to be passed in.

**Comment by Turbo87** [comment]
how is this different from `getContext().element`?

**Comment by rwjblue** [comment]
It isn’t, but there is some issues that folks will have  to deal with there. For example, if this isn’t a test setup with setupTest, setupRenderingTest, setupApplicationTest (e.g. a plain QUnit test, or a legacy `moduleForAcceptance` test) doing `getContext().element` would result in a very obtuse error message (`element of undefined` or some such).
