### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#285]
We need to generate a nice set of detailed API docs for the functionality in this library. 

- [ ] Add in-line API docs for all public APIs in `addon-test-support/@ember/test-helpers`
- [x] Add API doc generator (likely publishing to GH Pages).

**Comment by Turbo87** [comment]
@samselikoff would https://github.com/ember-learn/ember-cli-addon-docs already be an option?

**Comment by rwjblue** [comment]
Landed docs for the DOM interaction helpers in https://github.com/emberjs/ember-test-helpers/pull/287.

**Comment by samselikoff** [comment]
@Turbo87 yes, it is functional! We are trying to round it out but if you/someone wants to use it now I will be happy to discuss/pair with you.

You can look at https://ember-learn.github.io/ember-cli-addon-docs/ for reference (and the corresponding dummy app in the source code to see how its built)
