### ISSUE TITLE
Support non ember-data models

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember-test-helpers#29]
Files in the `models` folder currently get nerfed due to: https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-model.js#L41

Error:

```
Error: Assertion Failed: `(unknown mixin)` does not appear to be an ember-data model
    at new Error (native)
```

**Comment by rwjblue** [comment]
I would use `moduleFor('model:post')` in a non-ED scenario.

We can provide a nice helpful assertion though, when you call `moduleForModel` on a non-ED model, what is the "proper" way to detect if a given factory is an Ember Data model?

**Comment by fivetanley** [comment]
`store.modelFactoryFor('post') instanceof DS.Model` ?

**Comment by walter** [comment]
:+1: for implementing something that is agnostic. I'm using ember-orbit with ember-mocha and was surprised by describeModel (which wraps moduleForModel) breaking on the ED dependency.

**Comment by rwjblue** [comment]
We'd happily review a pull request with a proposed solution.

**Comment by walter** [comment]
Thx @rwjblue, I appreciate your and the rest of contributors' work on this.

I realize I'm not contributing much by simply adding my voice in support of the issue, but the intention is to show that there people who would like this, too.

If I had the means to add a PR for this right now, I would. I'm a long time open source maintainer myself and I realize how much more valuable contributed code is. Having said that, I do believe it is perfectly valid to add to a project by voicing your needs. You, of course, have no obligation to implement what I ask for. I do not feel entitled to anything in regards to the project.

Hey, at least I didn't create a NEW issue without searching existing issues that address my concerns first!

**Comment by rwjblue** [comment]
I am very sorry if that last comment came off as snarky or negative. I was basically saying that I would definitely be open to a fix, just haven't had time (or a personal need) to dig into it myself yet.

**Comment by walter** [comment]
All cool. No worries. I was just leaving a little something behind to show that I appreciate the work on this instead of just being a [help vampire](http://www.skidmore.edu/~pdwyer/e/eoc/help_vampire.htm).

**Comment by rwjblue** [comment]
This should be addressed when using the new testing APIs provided by ember-qunit (e.g. moduleForModel is no longer "a thing").

Closing....
