### ISSUE TITLE
Arbitrary arguments to `wait` cause error

### ISSUE THREAD

**Issue by simonihmig** [emberjs/ember-test-helpers#300]
Seems since this [commit](https://github.com/emberjs/ember-test-helpers/commit/0a83ee3b822f59813baf71bc50938cc71e70f1b4) where `wait` delegates to `settled`, passing a non-object (e.g. boolean) to `wait` would cause a `Cannot use 'in' operator to search for 'waitForTimers' in true` error. Prior to this, this would work (the argument would simply have no effect).

Offending line: https://github.com/emberjs/ember-test-helpers/blob/9eb3e32f8340d01704e950f317b282f07073f1e9/addon-test-support/%40ember/test-helpers/settled.js#L171
Example: https://travis-ci.org/kybishop/ember-popper/jobs/328856339#L547
Caused by: https://github.com/kybishop/ember-popper/blob/5d4457588fd9f30f7a0a2aa34a28e86209ae5978/tests/integration/components/ember-popper/action-test.js#L46

**Comment by rwjblue** [comment]
Great sleuthing. There is another reported issue around this same sort of thing (though I didn’t know it was related until you tracked down the problem). 

The fix here should be to check the arg is an object and not-null before checking for options...
