### ISSUE TITLE
Wildcard export incompatible with projects on Ember CLI below 2.12

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#311]
- Ember CLI before v2.12 transpiled ES6 modules on its own by using Babel 5, since Ember CLI v2.12 the `ember-cli-babel` version of the addons themselves are responsible for that.

- Babel 5 has a broken implementation of compiling wildcard exports

This leads to the wildcard export in `ember-test-helpers/index.js` not being transpiled properly for projects on Ember CLI below 2.12 (see also https://github.com/simplabs/ember-hbs-minifier/pull/25).

There are two solutions to this:

1) declare v0.7.0 of this addon as only compatible with Ember CLI 2.12+

2) explicitly declare all reexports in `ember-test-helpers/index.js`

**Comment by rwjblue** [comment]
I think we should do option #2 above, and add a test that uses manual require to confirm all exports from `@ember/test-helpers` are available from `ember-test-helpers`...

**Comment by Turbo87** [comment]
https://github.com/emberjs/ember-mocha/pull/188 works around this issue so this is not quite as important anymore. I'm not sure if `ember-qunit` is still importing from `ember-test-helpers` though.

**Comment by Turbo87** [comment]
closing this as https://github.com/emberjs/ember-mocha/pull/188 seems to work fine and no one else seems to be complaining about it :)
