### ISSUE TITLE
`options` parameter for `settled` helper is not documented

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#314]
The `settled()` helper function has an optional `options` parameter that can be used to configure what to wait for. Unfortunately this parameter is not documented yet.

**Comment by rwjblue** [comment]
It is private API (to support the old `wait()` API) and will be deprecated. It was intentionally undocumented for that reason.

This is what I was saying in https://github.com/emberjs/ember-test-helpers/pull/303#issuecomment-359176430...

**Comment by Turbo87** [comment]
oh, I see, nevermind then...
