### ISSUE TITLE
[0.7.17] waitUntil timed out

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember-test-helpers#318]
We upgraded to `0.7.17` and we started getting this error (`waitUntil timed out`) in a bunch of tests. Seemingly sporadically. We have a test like this:

```coffeescript
  @set('person', EmberObject.create(name: 'Conan'))

  @render hbs '{{some-component person.name}}'
  @set('person.name', 'Jay')

  await wait()
  assert.equal @$().text().trim(), 'Jay created this'
```

Which started sporadically failing (on the `await wait()` line) with that error. Not sure if we are using it wrong or there is some bug.

Another funny thing is that if I remove the `await wait()` line, not only is the error not received any more (which is normal), but also the test passes... I have no idea why. Is this normal? Is this documented somewhere?

Thanks!

P.S. Alongside `ember-test-helpers`, `ember-cli-qunit` got updated from `4.3.0` to `4.3.1` and `ember-qunit` from `3.3.0` to `3.3.1`. Not sure if this matters as I'm seeing here commits that are related to `wait` so I guess the issue is here (or in our code).

**Comment by rwjblue** [comment]
Any chance you can work up a reproduction?

**Comment by rwjblue** [comment]
There were definitely changes in wait’s internal implementation, but based on what we did it should have been the same underlying code as before.

**Comment by boris-petrov** [comment]
I tried creating a new Ember app and adding some code to reproduce it but it seems to work in a new project. What I noticed is that if I run **only** these tests, they pass. However, if I run our complete test suit, they fail. So maybe my reproduction should be with more stuff inside...

But the tests seem to fail **every** time. Also, it's strange - on my computer, if I remove the `wait()` call from the failing test, the other one in the same file fails. If I also remove `wait` from it, all tests pass. But on the integration server even without those two tests other ones fail (in a different file and used in a completely different way). Not sure why there is such a difference... both are Linux machines (although mine is Arch and the CI is Ubuntu).

If you give me any steps to try to debug on my machine, I could help with that. I'm not sure I'll be able to create a reproduction easily unfortunately.

**Comment by rwjblue** [comment]
We need to figure out why `wait` is timing out. You can put a breakpoint around here https://github.com/emberjs/ember-test-helpers/blob/7a92c721f8e55096a7bdb217e7cd294102aa82f8/addon-test-support/ember-test-helpers/wait.js#L34, and see what is still waiting (e.g. returning false).

**Comment by rwjblue** [comment]
Ugh. Looks like I messed up when refactoring, and forgot to add `{ timeout: Infinity }` to the `waitUntil` invocation.

**Comment by boris-petrov** [comment]
@rwjblue - yes, manually adding that argument to `waitUntil` fixes the issue on my side. You're going to publish a new version soon, I guess?

Thanks for the support and taking the time to dig into that!

A side note - the CSS of the test runner seems completely broken in Chrome when running `ember test`. It wasn't like that before. I have no idea what could have broken it - in which repo should I create an issue?
