### ISSUE TITLE
installing into Ember 2.18 addon breaks all tests

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember-test-helpers#323]
This seems like the same symptom as emberjs/ember-qunit#179.

Every unit and integration test now fails with `undefined is not an object (evaluating 'module.setContext')`. or `you must set a resolver with testResolver.set(resolver)`

The only change from tests running as normal was
`ember install ember-test-helpers`

**Comment by BryanCrotaz** [comment]
`npm uninstall ember-test-helpers`
makes the tests pass again.

**Comment by BryanCrotaz** [comment]
Reproduction:
```
ember addon repro-test-helper-bug
cd repro-test-helper-bug
ember g service example
ember serve
```
At this point all tests pass in the browser
```
ember install ember-test-helpers
ember serve
```
Now tests are broken as above.

**Comment by BryanCrotaz** [comment]
@rwjblue managed to create a reproduction of the bug I originally reported elsewhere

**Comment by BryanCrotaz** [comment]
`v0.6.3` doesn't cause the problem

**Comment by BryanCrotaz** [comment]
using latest master fails even worse:
```
Bryans-MacBook-Pro:repro-helpers-bug bryan$ ember s

Missing npm packages: 
Package: ember-test-helpers
  * Specified: git@github.com:emberjs/ember-test-helpers.git
  * Installed: (not installed)

Run `npm install` to install missing dependencies.



Stack Trace and Error Report: /var/folders/24/9c9x7j316gbd3z5wg84fghqc0000gn/T/error.dump.2b0d032746e946ea838b9cec63be2ce1.log
An error occurred in the constructor for ember-cli-dependency-checker at /Users/bryan/Projects/repro-helpers-bug/node_modules/ember-cli-dependency-checker
```

**Comment by BryanCrotaz** [comment]
Works when installed via ember-qunit

**Comment by Turbo87** [comment]
@BryanCrotaz the way this project should be used is through `ember-qunit` (or soon also `ember-mocha`), but you should **not** add an explicit dependency on it to your `package.json`. I guess the documentation on this needs to be a little more clear 🤔

**Comment by rwjblue** [comment]
It does seem odd to me that installing it as a direct dependency somehow makes it break though.

**Comment by BryanCrotaz** [comment]
I would assume `ember-qunit` uses v0.6.3. v.7.x is badly broken by the looks of things.

**Comment by Turbo87** [comment]
nope, `ember-qunit` uses v0.7.x. the older v0.6.x branch is not an Ember addon, so installing it does not actually have any effect.

**Comment by Turbo87** [comment]
@rwjblue do we plan on fixing the situation or should we close this now that #334 is merged in?

**Comment by rwjblue** [comment]
I think we should prevent conflicting versions via an init time assertion or something

**Comment by stefanpenner** [comment]
I don't believe we support this version any longer, due to this I believe we should close this issue. Please respond if you think I closed this in error
