### ISSUE TITLE
Issues Upgrading To 4.3.1 & 2.18 / leakiy state & Ember Simple Auth

### ISSUE THREAD

**Issue by alexander-alvarez** [emberjs/ember-test-helpers#324]
This the provided case fails because it is using the real session service provided by ember simple auth
https://github.com/alexander-alvarez/ember-cli-qunit-service-registering/compare/572fae2
Removing the application route mixin causes the test case to fall
https://github.com/alexander-alvarez/ember-cli-qunit-service-registering/compare/572fae2...7bbd425

Analysis extracted from  slack:
>https://github.com/ember-cli/ember-new-output/blob/master/tests/test-helper.js#L6 sets the application so 
https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/@ember/test-helpers/setup-context.js#L167 has a real application which runs the initializers once before all the tests suites (didn't use to occur)
https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/engine.js#L136
which in turn triggers
https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/application-route-mixin.js#L87 & https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/computed.js#L339
so even though I override it https://github.com/alexander-alvarez/ember-cli-qunit-service-registering/compare/test-case-failing?expand=1#diff-6902ce6b3192309e4080d20541f6fbfdR13
it hits the cached version

I'm not sure if the issue is here, or somewhere else, but I wanted to document it for posterity.

**Comment by Turbo87** [comment]
@alexander-alvarez I think this is an issue with `ember-simple-auth`, that basically looks up the session service before you're able to register a custom one. Have you tried their most recent release?

**Comment by alexander-alvarez** [comment]
Yup I'm using latest https://github.com/alexander-alvarez/ember-cli-qunit-service-registering/blob/test-case-failing/package.json#L40
but now that I look it relates to https://github.com/simplabs/ember-simple-auth/issues/1539
I started researching before that issue was open :sob: 
continuing discussion over there...
