### ISSUE TITLE
Replacement for `this.$()`

### ISSUE THREAD

**Issue by nlfurniss** [emberjs/ember-test-helpers#327]
Currently, there isn't a great replacement for `this.$()` in integration tests. What you have to do now is `find(.class, this.element || this_element)` (depending on our version of ember-qunit). Additionally, the `ember-test-helpers-codemod` does not handle this case, which makes switching away from the jQuery helpers tedious and a lot more work.

What do you think about adding a `findInComponent` integration helper?

**Comment by Turbo87** [comment]
you can do `this.element.querySelector()` instead

**Comment by nlfurniss** [comment]
Well I'd have to do `this._element` since we're ember-qunit@2. And then when we want to upgrade, we'd have to find/replace everything.

But my larger concern is being able to code-mod these changes. We're going to have to change 10K tests, and the code-mod has been a sanity-saver. Having to run the code-mod, clean up the code, then adding an extra step of doing my own find/replace with `this._element.querySelector` makes removing jQuery that much more difficult.

**Comment by Turbo87** [comment]
if you're using `ember-qunit@2` you can't use `@ember/test-helpers` anyways 🤔 

I would recommend to use https://github.com/simplabs/qunit-dom for assertions, which should work with both variants. see also https://github.com/ember-cli/rfcs/pull/116

**Comment by nlfurniss** [comment]
We're using `ember-native-dom-helpers` currently, but since this is more or less a port of that, once we move to ember-qunit@3 then utilizing this addon will be simple.

Thats a totally different library, and would be a much larger change than running a code-mod over a lot of tests.

Can you help me better understand your reticence to something like `findInComponent`?

**Comment by Turbo87** [comment]
we already have `find` and `this.element.querySelector()`. I just don't see a reason to add yet another API for the same thing.

**Comment by nlfurniss** [comment]
@Turbo87 `if you're using ember-qunit@2 you can't use @ember/test-helpers anyways 🤔`

Why is that? And is it documented anywhere?

**Comment by Turbo87** [comment]
because https://github.com/emberjs/ember-qunit/commit/98f6bbc7b45d26fc6b9178edd3bc251efbc34602 added the dependency and the first release to include this was v3.0.0-beta.3
