### ISSUE TITLE
Using global DS is deprecated

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember-test-helpers#329]
Found this while searching for possibilities for deprecation warning.

```
build-registry.js
test-module-for-model.js
```

**Comment by rwjblue** [comment]
Hmm. Thanks for reporting! I think we can figure out a path forward by attempting to require the `ember-data` module before falling back to `window.DS`...

**Comment by stefanpenner** [comment]
I believe we are safely free of this now, so I will be closing this. If I am closing in error, please respond and help me understand why, so I can reopen and address :)
