### ISSUE TITLE
README: Add "Do not add this as a dependency" note

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#333]
Since a lot of people seem to fall into that trap we should add a big fat note to the README that tells the readers to not add this as a direct dependency to their projects, but instead rely on `ember-qunit` (and soon `ember-mocha`) to provide it.

**Comment by rwjblue** [comment]
IMHO, it shouldn’t matter to install it as a dependency. We should figure out what causes failures and fix it. Barring that, we should actually error if it is installed incorrectly.
