### ISSUE TITLE
CI test suite is broken with latest QUnit release

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#335]
The latest QUnit release is now verifying that when `assert.step()` was called you must also call `assert.verifySteps()` later (see https://github.com/qunitjs/qunit/pull/1252). Unfortunately that breaks our assumptions and the "instrumented element" test abstraction we use to verify the events that an element emits. In some tests we use these instrumented elements without verifying the event order at the end which is now causing issues due to the QUnit changes.

There are a few potential solutions:

- Run `assert.steps = []` in the `afterEach` blocks to work around the new assertion (`assert.steps` appears to be private API though)

- Use instrumented and regular elements depending on the test

- Run `assert.verifyStep()` at the end of all tests even though the results don't actually matter to that test

IMHO none of those solutions are really great, but we will need to find/choose one to unblock our CI 🤔 

/cc @rwjblue

**Comment by snewcomer** [comment]
@Turbo87 Anything help I can provide or is this mainly a Robert question?  I might be in favor of # 3 though.

**Comment by Turbo87** [comment]
@snewcomer I guess any solution is better than no solution, so if you can work on a PR that unblocks CI that would be wonderful :)
