### ISSUE TITLE
Adding drag and drop helper

### ISSUE THREAD

**Issue by jhitchins88** [emberjs/ember-test-helpers#337]
There is a lot of functionality that involves drag and drop, especially on touch-screens.  Would this kind of helper be welcome here?  If so, I could throw up a PR of what I have on my own project so other people could take a look.

**Comment by Turbo87** [comment]
@jhitchins88 this does not seem like something most apps would need, but with the way the new helpers work it's relatively easy to provide drag and drop test helpers in a dedicated Ember addon instead :)

**Comment by jhitchins88** [comment]
Awesome.  Thanks for the input.
