### ISSUE TITLE
Add `clickOver` helper

### ISSUE THREAD

**Issue by jacobq** [emberjs/ember-test-helpers#338]
I sometimes find that I need to simulate a user clicking on something that has a transparent element "on top of" it (e.g. [plotly.js "coverslip" element](https://github.com/plotly/plotly.js/blob/13eb982ec9700ee9fe6cb8a93ee12d4ee8b0a215/src/components/dragelement/index.js#L32-L41)). Would it make sense to include a helper for that in this repo or is that something that would be better in an addon? (Maybe it should be decomposed even further to just `getElementOver(element)`...) I'd just like to get some feedback to help me decide how I should approach this. Thanks in advance.

The implementation could be something like this:

```js
import { click } from '@ember/test-helpers';

/**
  This helper is similar to `click` but rather than dispatching the event
  to the target element directly, it uses `document.elementFromPoint`
  to find the element that would receive a real click if the pointing device
  were to be clicked at the location of the center of the target element.
  
  @public
  @param {Element|string} target the element or selector to click "over"
  @return {Promise<void>} resolves after settling
*/
export default function clickOver(elementOrSelector) {
  const target = typeof elementOrSelector === 'string' ?
    document.querySelector(elementOrSelector) : elementOrSelector;
  const { x, y } = getCenter(target);
  const clickElement = document.elementFromPoint(x, y);
  if (!clickElement) {
    throw new Error(`Could not identify element at (${x},${y})`, clickElement);
  }
  return click(clickElement);
}

function getCenter(target) {
  const rect = target.getBoundingClientRect();
  return {
    x: rect.x + rect.width/2,
    y: rect.y + rect.height/2
  };
}
```

**Comment by Turbo87** [comment]
This seems like a quite specific requirement and something that is well suited to be put in an addon for example. I'm not sure it belongs into `@ember/test-helpers` itself though.

**Comment by jacobq** [comment]
Fair enough. Do you know of any other packages that contain test helpers like this (i.e. a potentially good home for it)? When searching GitHub I found https://github.com/201-created/ember-cli-acceptance-test-helpers though it looks like it hasn't been updated for the newer test API. I guess if no one else seems to need something like `clickOver` I will just keep it with the project where I'm using it.
