### ISSUE TITLE
Publish latest version to NPM

### ISSUE THREAD

**Issue by dzbo** [emberjs/ember-test-helpers#342]
I see that latest published version to npm is `0.7.0-beta.4` where latest now is `0.7.18`

![Alt text](https://monosnap.com/file/SLeVuG6iJLQHg4WmOer3KZTZjxV8Ay.png)

**Comment by rwjblue** [comment]
The package name was changed to `@ember/test-helpers`.

**Comment by dzbo** [comment]
Ops didn't know, thanks!

**Comment by Turbo87** [comment]
I've reset the `latest` dist-tag of `ember-test-helpers` to v0.6.4 so that it's hopefully less confusing

**Comment by rwjblue** [comment]
Good idea @Turbo87
