### ISSUE TITLE
0.7.19 breaks tests

### ISSUE THREAD

**Issue by mydea** [emberjs/ember-test-helpers#345]
I've just updated one of our apps, in the process of which @ember/test-helpers was also updated form 0.7.18 to 0.7.19. This broke our entire test suite, with the following error:

```js
Could not find module `@ember/test-helpers` imported from `dummy/tests/test-helper`
```

Downgrading to 0.7.18 fixed the issue.

**Comment by Turbo87** [comment]
v0.7.19 was a broken deployment for some reason. we just published v0.7.20 to fix this.
