### ISSUE TITLE
non-jQuery pending requests

### ISSUE THREAD

**Issue by amk221** [emberjs/ember-test-helpers#347]
This demo app [https://github.com/amk221/-ember-fetch-pending-count](https://github.com/amk221/-ember-fetch-pending-count/commit/a2ed50285164ae677118d357deae1bb6df17b446#diff-2168f026d657db1526ae92392f844a3fR5)
shows that I cannot use `pendingRequestCount` with `ember-fetch` because `ember-test-helpers` only considers requests made via jQuery when monitoring AJAX requests.

**Comment by rwjblue** [comment]
ember-fetch adds a custom test waiter specifically to handle this case. You are definitely correct it is not considered “pending ajax” but `await settled()` should definitely wait for any `fetch`s that are done from ember-fetch...

**Comment by amk221** [comment]
It does add a custom waiter, but this test case shows a scenario which is not possible.
https://github.com/amk221/-ember-fetch-pending-count/commit/a2ed50285164ae677118d357deae1bb6df17b446#diff-8d9f64b99fb73be5388818039649c82fR13

I can easily work around it though...

**Comment by rwjblue** [comment]
Wouldn’t it be better (and less implicit) to control the requests and only resolve them once you’ve confirmed that you are in the right place?

**Comment by amk221** [comment]
Ok, but I just raised the issue anyway, because more and more people will be phasing out jQuery from their apps, and this is something that no longer works, so ¯\_(ツ)_/¯
