### ISSUE TITLE
find and findAll helpers do not use HTML element context properly

### ISSUE THREAD

**Issue by jbingham94** [emberjs/ember-test-helpers#351]
It seems that both the `find` and `findAll` helpers do not properly use context if you pass in an HTML element.  For example:

```javascript
find('.my-selector', myHTMLElement); // I want to look for .my-selector within myHTMLElement
```

Instead of looking within myHTMLElement, the helpers seem to look within the first element with myHTMLElement's selector.  When I switch back to using `find` from ember-native-dom-helpers, the above code works properly.

**Comment by Turbo87** [comment]
the reason for this is that the `find()` functions in this library here don't have a `context` parameter. see https://github.com/emberjs/ember-test-helpers/blob/master/API.md#find

**Comment by jbingham94** [comment]
@Turbo87 Thanks for clearing that up. I don't feel like this would be super tough to implement, and it would definitely be a very helpful feature, as almost every find/findAll we do has some sort of context.  This limitation is pretty much the only thing stopping us from ditching ember-native-dom-helpers completely.

**Comment by synaptiko** [comment]
Are you willing to reconsider adding `context`? It would match quite well with `assert.dom()` from `qunit-dom`.

**Comment by Turbo87** [comment]
qunit-dom is doing a bit more and have a slightly different API though.

instead of `find('.my-selector', myHTMLElement);` you can just use `myHTMLElement.querySelector('.my-selector');`

**Comment by rwjblue** [comment]
To reiterate from prior conversations on this, the `find` / `findAll` variants should generally only be used in tooling without access to the test context directly, user-land test code should totally use `this.element` directly.

The path forward here to prevent accidental trollage is to trigger an error when passing a second argument. As mentioned in https://github.com/emberjs/ember-test-helpers/issues/351#issuecomment-377321867.

**Comment by synaptiko** [comment]
@rwjblue We recently refactored our addons and apps from Ember 2.18 to 3.5. Usage of `find`/`findAll` vs `this.element.querySelector/All` was one of the things we were considering but it wasn't clear to us that `find`/`findAll` is not intended to be used by user-land test code. Especially when the default behavior of https://github.com/simonihmig/ember-test-helpers-codemod is usage of `find`/`findAll`. There is an additional codemod to convert it to `this.element`. This was something which confused us.

**Comment by rwjblue** [comment]
The _most likely_ reason for it to transform to `find` is just that it is easier to codemod (you don't have to worry about tracking which `this` context a given invocation has to know if you can use `this.element` or not), but lets move the convo about the codemod over into simonihmig/ember-test-helpers-codemod...

**Comment by rwjblue** [comment]
> If Ember team wants to push away from jQuery towards using native querySelector/querySelectorAll, why is there even an effort to create find/findAll helpers?
> Shouldn't the native way also be the one to use in tests?

Yes! That is exactly what I said in https://github.com/emberjs/ember-test-helpers/issues/351#issuecomment-456881507 above, in both of the RFCs ([emberjs/rfcs#268](https://emberjs.github.io/rfcs/0268-acceptance-testing-refactor.html) and [emberjs/rfcs#232](https://emberjs.github.io/rfcs/0232-simplify-qunit-testing-api.html)) and in https://github.com/emberjs/ember-test-helpers/issues/278.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember-test-helpers/pull/358 implemented assertions that I was referring to in https://github.com/emberjs/ember-test-helpers/issues/351#issuecomment-456881507. Closing...
