### ISSUE TITLE
Compatibility with ember 1.13

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/ember-test-helpers#357]
As this issue suggests, ember-test-helpers isn't compatible with ember 1.13: https://github.com/ember-cli/ember-try/issues/187
Isn't there a way we could write some fallback code for that case?

If someone could explain me the details I'd be willing to try a PR.

Thanks!

**Comment by rwjblue** [comment]
The newer style tests do not (and almost certainly will not) support Ember older than 2.4, however usage of `moduleForComponent` / `moduleForAcceptance` / `moduleFor` should continue to work properly with 1.13 as far as I know (though we do not test older than 2.0).

Please provide a reproduction if you'd like guidance on how to fix a specific thing...

**Comment by Turbo87** [comment]
@rwjblue IIRC the old style things also only work when using `setResolver()` instead of `setApplication()`. we had similar issues in `ember-test-selectors`.

**Comment by stefanpenner** [comment]
Unfortunately, I do not believe we will be supporting this version any longer. It is out of our official support window, and unfortunately at this time may not have the resources to support it officially.
