### ISSUE TITLE
setting this.render is broken in 0.7.21

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember-test-helpers#359]
https://github.com/kellyselden/ember-test-setup/blob/master/addon-test-support/-setup-render.js#L9 was working on the assumption in 0.7.20 that I could override `this.render`. It was broken in https://github.com/emberjs/ember-test-helpers/pull/349. I understand why it was changed, but it sucks I can't have my desired API anymore.

**Comment by Turbo87** [comment]
I'm somewhat surprised that that API has ever worked :D

**Comment by rwjblue** [comment]
IMHO, using `this.render` from this library should actually be deprecated. Folks should be `import { render } from '@ember/test-helpers'`...

@kellyselden - That change was added for good reason (folks were clobbering things in a way that left them in a horribly broken state and they had no clue).  I don't really know how to weigh the volume of that vs the volume of the users of ember-test-setup. If we need to treat this as a regression we should allow clobbering `this.render` but emit a deprecation/warning when it happens...

**Comment by kellyselden** [comment]
@rwjblue You mean a deprecation when this.render from this library is run, not when this.render is set, correct?

**Comment by rwjblue** [comment]
@kellyselden - I think I meant both?

**Comment by kellyselden** [comment]
@rwjblue Hmm I guess that would be ok. So then users of ember-test-setup would get deprecations until this.render is removed from here, then the warnings would disappear?

**Comment by Turbo87** [comment]
FWIW I'm pretty opposed to reverting this. We have implemented these guards for a good reason and I don't think people should ever override the functions that we set up here. If `ember-test-setup` did that, then we should think about a better API for that addon, that does not involve overwriting functions from `@ember/test-helpers`.

**Comment by rwjblue** [comment]
I tend to agree @Turbo87. IMHO a better (more aligned API) would be for users of ember-test-setup to use an imported `render` helper from that addon...

**Comment by Turbo87** [comment]
@kellyselden I still think you shouldn't overwrite `this.render()`, but I guess https://github.com/emberjs/ember-test-helpers/pull/374 may have opened a loophole for you. Closing this issue now.
