### ISSUE TITLE
Cannot test "loading" state of components

### ISSUE THREAD

**Issue by jamesarosen** [emberjs/ember-test-helpers#372]
I have a component that loads some data asynchronously:

```js
data: null,

url: computed({
  get() { return null },

  set(_, newValue) {
    this.set('loading', true)
    run.scheduleOnce('actions', () => {
      this.ajax.request(newValue).then((data) => {
        this.set('loading', false)
        this.set('data', data)
      })
    })
  }
})

layout: hbs`
  {{if loading 'Loading…'}}
  {{data}}
`
```

I want to test that "Loading…" appears during loading:

```js
let deferred
server.get('/some/url', () => {
  return (deferred = RSVP.defer).promise
})
assert.equal(this.$().textContent, 'Loading…')
deferred.resolve(new Mirage.Response(...))
assert.equal(this.$().textContent, 'the response')
```
Unfortunately `await render(...)` pauses until `request(...)` resolves, so the test hangs.

May be related to #281

**Comment by cibernox** [comment]
First, doesn't `scheduleOnce` need to receive the name of the queue as first argument? Something like `scheduleOnce('afterRender', fn)`.

Secondly, the trick is that although you wait for rendering in 99% of the tests, you can choose not to.

```
let renderPromise = render(hbs`{{my-component}}`)

await waitUntil(() => this.element.textContent.trim() === 'Loading…'); // This will wait until the loading message appears
// assert something else if you want
deferred.resolve(new Mirage.Response(...))
await renderPromise;
assert.equal(this.$().textContent, 'the response')
```

**Comment by jamesarosen** [comment]
> First, doesn't scheduleOnce need to receive the name of the queue as first argument? Something like scheduleOnce('afterRender', fn).

It sure does. Sorry, I mis-adapted my code for the issue. I've added the `'actions'` argument to the above code.

Great suggestion on moving the `await`. That, of course, works perfectly 😀

I do think this is an improvement over the old behavior. It is, however, a _change_.

**Comment by cibernox** [comment]
Yes, previously with the `andThen` helper it was impossible to test intermediate states. 
Now with explicit `await` you choose when you want to wait for the world to settle.
