### ISSUE TITLE
Should get-root-element use Ember.getOwner()?

### ISSUE THREAD

**Issue by apellerano-pw** [emberjs/ember-test-helpers#375]
I tried replacing some of my ember-native-dom-helpers `click` calls with ones from `@ember/test-helpers` today and converted tests would complain:

`Must setup rendering context before attempting to interact with elements.`

These are very simple tests, e.g.
```javascript
it('tests something or other', async function () {
  this.render(hbs`{{my-component}}`);
  await click('button');
  expect(something).to.be.true;
});
```

Any idea what's going wrong? I dug into [dom/get-root-element.js](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/dom/get-root-element.js#L14) a bit and if I remove the falsey check on `owner` (and the error it throws) the tests pass because a later second falsey check on `owner` defaults the selector to `#ember-testing` which is accurate for my environment.

We use ember-cli-mocha (0.15.0)

**Comment by rwjblue** [comment]
The error is generally there for good reason. It’s to ensure that you only use this libs DOM helpers when your test is itself setup in the correct way.

**Comment by rwjblue** [comment]
If you are using the DOM helpers from here you have to be using Ember-mocha@0.14.0-beta.1 or higher, and setting up with the correct methods. Can you share your test setup?

**Comment by apellerano-pw** [comment]
Ahh, that must be it.

My current tests/test-helper.js is
```javascript
import resolver from './helpers/resolver';
import { setResolver } from 'ember-mocha';

setResolver(resolver);
```

But the example in the ember-mocha docs looks different.

I'll start barking up that tree and post a working config here when I get it working

**Comment by apellerano-pw** [comment]
Ok I dug into this some more and my setup seems correct after reading all the documentation. I'm doing an integration test if it matters.

I see that when [dom/get-root-element.js](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/dom/get-root-element.js#L11) is looking for the owner it checks `context.owner` but my context appears to have its owner set via `Ember.setOwner` in [test-module.js](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/ember-test-helpers/legacy-0-6-x/test-module.js#L132) which is gonna use the `OWNER` symbol thingy to set it on a property like `__OWNER__123456789`.

If I replace the line attempting to set the owner in `getRootElement()` with
```javascript
let owner = context && Ember.getOwner(context);
```

my tests pass again. Could this be necessary or am I still working around some error somewhere else in my app?

**Comment by guangda-prosperworks** [comment]
@apellerano-pw I guess you could send a PR to fix this :p

**Comment by apellerano-pw** [comment]
@guangda-prosperworks I had started down that path but all the qunit tests fail if I make the change to `getOwner`. It looks like the [RFC](https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md#setuptest) for the testing unification specifies that an `owner` object should exist, so this library is working correctly. I dug into ember-mocha's implementation of this addon and it turns out you have to use `setupTest` in a new way to opt-in to the test unification changes. There's a migration guide in the docs folder https://github.com/emberjs/rfcs/blob/master/text/0232-simplify-qunit-testing-api.md#setuptest

I haven't had the time to sit down with the guide and follow thru on it yet, but I'm confident it will fix my issue.  I'm gonna close this issue, hope it helps others!
