### ISSUE TITLE
Issue with blur() on textarea

### ISSUE THREAD

**Issue by timjcook** [emberjs/ember-test-helpers#381]
Issue: I can't seem to trigger a blur/focus out event on a `textarea` using the `blur()` method. I've applied the same pattern to `input` fields and it has worked as expected.

Example: I would expect the following to blur the `textarea`.
```
  await fillIn('textarea', 'My Input');
  await blur('textarea');  
```
Interestingly I was able to get my desired outcome by doing:
```
  await fillIn('textarea', 'My Input');
  await find('textarea').blur();
```
Which is very similar to what it seems `blur()` is doing under the hood.

As I mentioned I haven't had this issue on other input types like `input` or `select`.

**Comment by NullVoxPopuli** [comment]
I'm having a similar issue:
![image](https://user-images.githubusercontent.com/199018/41051049-0bae4ad4-6983-11e8-8fba-92f87ff37c98.png)

my test: 
import { stubService } from 'example-app/tests/helpers';

module('Integration | Component | todo', function(hooks) {
  setupRenderingTest(hooks);

  const inputSelector = 'input.edit';
  const labelSelector = 'label[data-test-todo-label]';
  const sampleTodo = { id: 1, text: 'Something that needs to be done' };
  const fakeChangeText = (assert: Assert) => (id: number, text: string) => {
    assert.equal(id, sampleTodo.id);
    assert.equal(text, sampleTodo.text);
  }


```ts
  test('input keypress enter | finishes editing', async function(assert) {
    assert.expect(5);

    stubService('todos', { changeText: fakeChangeText });

    this.set('testTodo', sampleTodo);
    await render(hbs`<Todo @todo={{testTodo}} />`);
    await triggerEvent(labelSelector, 'click');

    assert.ok(
      this.element.querySelector(editingSelector),
      'clicking the label should trigger editing'
    );

    await settled();

    assert.equal(document.activeElement, find(inputSelector), 'input should have focus after the label is clicked');
    find(inputSelector).blur();
    // https://github.com/emberjs/ember-test-helpers/issues/381
    await blur(inputSelector);

    assert.notEqual(document.activeElement, find(inputSelector), 'input should not have focus after a blur');
    await settled();
  });

// stubService:
import Service from '@ember/service';
import { getContext } from '@ember/test-helpers';

export const stubService = (name: string, hash = {}) => {
  let stubbedService = Service.extend(hash);

  let { owner } = getContext();
  owner.register(`service:${name}`, stubbedService)
};

export default stubService;

// component ts
export default class TodoItem extends Component {
  @service todos!: TodosService;
  todo!: Todo;

  @action
  didFinishEditing(e: KeyboardEvent) {
    const target = (e.target as HTMLInputElement);
    const text = target.value;

    this.todos.changeText(this.todo.id, text);
    this.doneEditing();
  }
 // ...
```
template:
``hbs
<div data-test-todo-id={{todo.id}} class="view">
  <input
    type="checkbox"
    checked={{todo.completed}}
    class="toggle"
    onchange={{action (mut todo.completed) value='target.checked'}} />

  <label data-test-todo-label {{action 'didClickLabel'}}>
    {{todo.text}}
  </label>

  <button class="destroy" {{action 'destroyTodo'}}></button>
</div>

{{input
  type='text'
  class='edit'
  value=todo.text
  blur=(action 'didFinishEditing')
  keyDown=(action 'handleKeydown')
}}
```

**Comment by NullVoxPopuli** [comment]
@timjcook hey, it looks like I have something working.... though it may be a false positive, I'm not sure yet. but I was successful in asserting that `blur` is indeed working... and the _behavior_ of my action is evaluating.... even though console.logs wouldn't print from within the action.

here is the updated code: https://github.com/NullVoxPopuli/react-vs-ember/blob/544d100d4983acb1ff6429ed36f2ea8b62b4b751/testing/ember/src/ui/components/todo/component-integration-test.ts

**Comment by timjcook** [comment]
@NullVoxPopuli Thanks for the feedback. Looks like our tests should be working as expected.

I've given it another go and switched back to my original test
```
await fillIn('textarea', 'My Input');
await blur('textarea');  
```
and it seems to be working fine, which makes sense because I couldn't see any issues when I had a look at the internals of the `blur` helper. My guess is it had something to do with my test server playing up and now it is behaving itself.

I'm satisfied that this is not a bug, what do you think? ok if I close it?

**Comment by NullVoxPopuli** [comment]
I'd say so, yeah. No bug

**Comment by rwjblue** [comment]
Thanks y’all!
