### ISSUE TITLE
click helper should ignore disabled inputs

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember-test-helpers#383]
`this.$('#foo').click()` and `document.getElementById('foo').click()` do nothing if the input is disabled. `await click('#foo')` still clicks disabled inputs. This is probably a bug.

**Comment by Turbo87** [comment]
Should it ignore the click or throw an error?

**Comment by kellyselden** [comment]
just ignore

**Comment by rwjblue** [comment]
We need to see what the DOM does natively (e.g. “real clicks”). You can slightly modify [the JSBin](http://jsbin.com/pulapatapo/1/edit?html,console,output) from #382 to test.

**Comment by kellyselden** [comment]
Just confirmed no events using that link
