### ISSUE TITLE
click() does not click some elements

### ISSUE THREAD

**Issue by medokin** [emberjs/ember-test-helpers#389]
We have updated our app and cli to 3.x. After days we managed to rewrite and run our acceptance tests, but the `click` does not work on some elements.

For Example:

while this does nothing
```js
await click('table tr.my-clickable-row');
```
this works
```js
$('table tr.my-clickable-row').click();
```

In other cases, when clicking a button, `click` seems to work.

**Comment by Turbo87** [comment]
@medokin can you reproduce in a fresh `ember new` app?

**Comment by medokin** [comment]
@Turbo87 Nevermind, it works fine in a fresh application. 

It has be a conflict with an addon...
