### ISSUE TITLE
getRootElement() fails when rootElement is an element

### ISSUE THREAD

**Issue by apellerano-pw** [emberjs/ember-test-helpers#403]
The `rootElement` documentation states it can be an element or a selector string, but `getRootElement()` only works with selector strings.

https://emberjs.com/api/ember/3.3/classes/Application/properties/rootElement?anchor=rootElement

We were testing out shadow DOM stuff in chrome and using an initializer to create the shadow DOM and then point `rootElement` to an element inside the shadow DOM. Unfortunately tests don't work because get-root-element.js only works when `rootElement` is a string that can be passed to a querySelector.

https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/dom/get-root-element.js#L21

If it's useful I can build an Ember Twiddle showing the crash

**Comment by rwjblue** [comment]
Welp. Thats just silly. Good catch, mind taking a shot at fixing?

**Comment by apellerano-pw** [comment]
Yeah I'll see what I can do
