### ISSUE TITLE
click use to take a context

### ISSUE THREAD

**Issue by atomkirk** [emberjs/ember-test-helpers#406]
with application tests, the old `click` helper took a context as a second argument. This was needed to test something like a third-party date picker that placed itself outside the test container right before the closing `body` tag. Without it, the selector of `click` won't find the date picker. 

Before I could do:

    click('.pika-next', 'body')

and it would find it. Now, if I do the same thing with the new click helper, it doesn't find it.

**Comment by rwjblue** [comment]
`click` accepts an element as an argument for these sorts of situations. For example, you could do this:

```js
await click(document.querySelector('body > .pika-next'));
```
