### ISSUE TITLE
What's needed for v1.0?

### ISSUE THREAD

**Issue by mike-north** [emberjs/ember-test-helpers#407]
Following SemVer, a 0.x release indicates

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

This package has been released [100 times as of the time of this post](https://github.com/emberjs/ember-test-helpers/releases). I have a feeling that the current API is stable. Is there something stopping a 1.0 release?

**Comment by rwjblue** [comment]
Not much. I'll make the next breaking change release 1.0.0.

**Comment by rwjblue** [comment]
v1.0.0 is released, see https://github.com/emberjs/ember-test-helpers/blob/master/CHANGELOG.md#v100-2018-10-29 for details.
