### ISSUE TITLE
`find` and `findAll` should allow for finding elements outside the root

### ISSUE THREAD

**Issue by alexlafroscia** [emberjs/ember-test-helpers#414]
When dealing with addons like `ember-pikaday` or `ember-wormhole`, it can be useful to allow for locating an element outside the root element of the test.

My proposal would be to allow a second parameter, like [`qunit-dom`](https://github.com/simplabs/qunit-dom/blob/master/API.md#assertdom), that allows you to override the "root element" to search.

If this is something you'd be interested in supporting, I'm happy to make a PR for it!

**Note:** I'm not suggesting we add the root-override behavior to _all_ helpers; it's easy enough to, for example, compose two together if you need to click something outside the root:

```javascript
const button = await find('.some-button', document.body);
await click(button);
```

**Comment by alexlafroscia** [comment]
I would propose to update the `getElements` helper to look something like this instead:

```javascript
function getElements(target, rootElement = getRootElement()) {
  if (typeof target === 'string') {
    return rootElement.querySelectorAll(target);
  } else {
    throw new Error('Must use a selector string');
  }
}
```

and then, where used in `findAll`, pass two arguments through rather than just the `selector`x

**Comment by rwjblue** [comment]
Hmm, why is a change needed here? What would adding a context parameter provide that "using the platform" doesn't?

```js
const button = await document.querySelector('.some-button');
await click(button);
```
