### ISSUE TITLE
Only jQuery.click() triggers error caught by assert.throws

### ISSUE THREAD

**Issue by nlfurniss** [emberjs/ember-test-helpers#453]
This [twiddle reproduces](https://ember-twiddle.com/de9115316563715af87fec8ddec9f796?openFiles=tests.integration.components.my-c-test.js%2Ctemplates.components.my-c.hbs) the issue.

### TLDR
There is a component that will throw an error if two attrs arent passed in (`x` and `y`) and the component is clicked on.

There are three tests:
1. Ensure no errors if both attrs passed in and component is clicked ✅
2. Ensure an error is throw when only one attr is passed in and component is clicked (**uses native JS and tests fails**) ❌
3. Ensure an error is throw when only one attr is passed in and component is clicked (uses jquery and test passes) ✅

Here is where things go wrong: 
```
// Qunit throws
try {
   block.call(currentTest.testEnvironment);  <====== This call doesnt trigger an error when it uses native JS. But FUN FACT: if you highlight this line at a breakpoint, it will log an error (???)
} catch (e) {
   actual = e;
}
...
if (actual) {     <==== `actual` needs to be set otherwise it wont catch the error and the test will fail.
```

_Originally posted by @nlfurniss in https://github.com/emberjs/ember-test-helpers/issues/310#issuecomment-412316982_

**Comment by NullVoxPopuli** [comment]
Hello! thanks for reporting!

I'm going to close this, as we have some new techniques for capturing errors now,
- see: https://github.com/emberjs/ember-test-helpers/issues/1128#issuecomment-1920196763


However, if you still feel something is missing feel free to open a new issue, and let's work on a more up to date repro of the problem :muscle: thank you!!! :heart: :partying_face:
