### ISSUE TITLE
add-ons unit tests fail to retrieve custom factories

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember-test-helpers#54]
Steps to replicate:
Create an ember-cli addon
Create a new file /addon/requests/foo
Create a new unit test /tests/unit/requests/foo

Use moduleFor('requests:foo') // This fails unless you also create /app/requests/foo

**Comment by Turbo87** [comment]
@olivierlesnicki that is the intended behavior. Only modules in the app tree are available in the Di container.
