### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#542]
- [x] `setupOnerror` should be included in the "test framework" section of API.md
- [ ] The `Parameters` entries in the Table of Contents on API.md really mess up the flow of reading the high level APIs that we provide. We should remove them...

**Comment by ygongdev** [comment]
Currently, the `documentation` module doesn't support modifying the `Table of Content`'s `depth`.
However, it seems like a quick trivial change. I created a small PR on `documentation` to try to get this going, https://github.com/documentationjs/documentation/pull/1215.

**Comment by rwjblue** [comment]
Awesome!
