### ISSUE TITLE
Document "integration: true" and "needs"

### ISSUE THREAD

**Issue by johnnyshields** [emberjs/ember-test-helpers#55]
I don't see any mention of `integration: true` or `needs` in the README for this lib. As I understand it those are the args for the methods in this lib.

Secondly, as an aside related to Ember itself, it would be better if we leveraged ES6's brilliant module functionality and **import** the modules which each model class needs in model class itself (like every other JS framework) rather than trying to be Ruby-esque and autoload the classes via a "Resolver". This would avoid the whole `integration` / `needs` stuff in the tests entirely.

**Comment by Turbo87** [comment]
@johnnyshields that would also make stubbing/mocking impossible or at least much harder compared to using dependency injection.

**Comment by rwjblue** [comment]
FWIW, emberjs/rfcs#229 makes `integration: true` the only non-deprecated path forward. 

`ember-test-helpers` is a lower level library that is leveraged by ember-qunit and ember-mocha. The README for [ember-qunit](https://github.com/emberjs/ember-qunit) includes documentation around `integration: true` at this point, so I'm going to go ahead and close this issue...
