### ISSUE TITLE
Add test and example to documentation of click / doubleClick with alt/cmd

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#551]
This should be possible as of https://github.com/emberjs/ember-test-helpers/pull/398, but we should confirm with a test and then add an exmaple to the API docs.

Tests are here:

https://github.com/emberjs/ember-test-helpers/blob/8d6352795d57aeb284b087ffc62b5a01d5b42476/tests/unit/dom/click-test.js#L99-L105

Docs are here:

https://github.com/emberjs/ember-test-helpers/blob/8d6352795d57aeb284b087ffc62b5a01d5b42476/addon-test-support/%40ember/test-helpers/dom/click.ts#L26-L56

**Comment by nummi** [comment]
> Use the `options` hash to change the parameters of the MouseEvents.

Maybe more text could be added here to explain that all event properties can be set here (I think that's the case). For example, I needed to test alt clicking a button and it wasn't clear to me you could simply do this: `click(el, { altKey: true })`.
