### ISSUE TITLE
Unit test for model requires inclusion of any other "referenced" model into needs.

### ISSUE THREAD

**Issue by abuiles** [emberjs/ember-test-helpers#6]
abuiles> dgeb: there is something else that has been buggy my and would like to hear your thoughts on, every time I create a unit test for a model, I have to put in need all the other models which it references in the belongsto  and hasMany  
6:24 PM <abuiles> all good until there
6:25 PM <abuiles> the really annoying part is that I also have to put all the model which those models reference so I end-up with a bunch of things in "needs" which are not necessarily related to the test  
6:26 PM <dgeb> abuiles: yeah, that's a real annoyance :/
6:27 PM <dgeb> we need smarter model tests
6:27 PM <dgeb> this shouldn't be necessary

**Comment by Turbo87** [comment]
https://github.com/emberjs/rfcs/pull/229 will finally fix this

**Comment by rwjblue** [comment]
RFC landed, closing...
