### ISSUE TITLE
setupOnError is not an exported member from '@ember/test-helpers'

### ISSUE THREAD

**Issue by theseyi** [emberjs/ember-test-helpers#617]
`import { setupOnerror } from '@ember/test-helpers'; // setupOnerror is undefined`

https://github.com/emberjs/ember-test-helpers/blob/master/API.md#setuponerror

**Comment by theseyi** [comment]
`"ember-cli-qunit": "^4.4.0"`

**Comment by rwjblue** [comment]
It is indeed exported, see here:

https://github.com/emberjs/ember-test-helpers/blob/0f9cf9a34e0c7f3e3ba54de74423353fb2434b45/addon-test-support/%40ember/test-helpers/index.ts#L24
