### ISSUE TITLE
triggerEvent cannot simulate a file input change event with an empty FileList

### ISSUE THREAD

**Issue by ggayowsky** [emberjs/ember-test-helpers#673]
triggerEvent cannot simulate the following case:
1. User open the file input selector and selects a file(s).
2. User opens the file input and hits cancel

Step 1 causes the input to fire a 'change' event with `event.target.files` to be a FileList with the selected file.
Step 2 causes the input to fire a 'change' event with `event.target.files` being an empty FileList.

In `fire-event.ts` the method `buildFileEvent` checks that the options.files is an array with at least one member. If options.files is an empty array, it does not update the files property on the event target. Because of this check cannot simulate the situation done as before.

Will try to get a fix & test in today.

**Comment by rwjblue** [comment]
Sounds great, definitely seems like a bug (wonder why we had that length check to begin with?)
