### ISSUE TITLE
`fillIn` ignores the `disabled` property on inputs

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember-test-helpers#680]
Even if an input is disabled, fillIn still lets you assign a value. I think this is a bug.

[Reproduction](https://github.com/jenweber/fillin-bug-repro) - see the [template with a disabled input](https://github.com/jenweber/fillin-bug-repro/blob/master/app/templates/application.hbs) and a [test that should not pass](https://github.com/jenweber/fillin-bug-repro/blob/master/tests/acceptance/inputs-test.js)

**Comment by ro0gr** [comment]
same issue exists for readonly inputs, which may lead to false positive tests

**Comment by rwjblue** [comment]
Ya, definitely would love to fix.

@ro0gr - Would you mind reviewing that PR to see if it also fixes that case?

**Comment by ro0gr** [comment]
oh, I haven't noticed the PR. Sure, I'll check it tomorrow!
