### ISSUE TITLE
TypeError: Class constructor Promise cannot be invoked without 'new'

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember-test-helpers#694]
I am seeing `TypeError: Class constructor Promise cannot be invoked without 'new'` when running ember beta or canary and including ie 11 as a target. It seems to bee coming from this file https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/-utils.ts

Not exactly sure what the issue is, as the built output looks much different, but perhaps someone here knows the issue?

You can see the failures here: https://github.com/ember-learn/ember-cli-addon-docs/pull/401

**Comment by amk221** [comment]
Also experiencing this, all my builds have started failing on Jenkins

**Comment by rwwagner90** [comment]
This was an issue in Ember itself. Should be fixed by https://github.com/emberjs/ember.js/pull/18281
