### ISSUE TITLE
How to select multiple?

### ISSUE THREAD

**Issue by ming-codes** [emberjs/ember-test-helpers#708]
Say that I have a `<select multiple>...</select>` element. The `fillIn` helper doesn't seem to work as it sets the `value` property. `click` just opens the dropdown.

**Comment by rwjblue** [comment]
We should probably create a helper _specific_ to `select`s. Using `fillIn` "feels" unusual, and also I don't think it fires all the right events.

**Comment by Mikek2252** [comment]
Are there any plans on how this should work, or is it okay for me to have a crack at creating this helper?

**Comment by ondrejsevcik** [comment]
Also the `fillIn` helper doesn't allow you to set `null`/`undefined`. If you have a select like this, you won't be able to select first option.
```hbs
<select>
  <option>-- select option --<option>
  <option value="1">Option 1</option>
  <option value="2">Option 2</option>
</select>
```
