### ISSUE TITLE
Deprecation: ember-cli-htmlbars-inline-precompile no longer needed

### ISSUE THREAD

**Issue by monkeywithacupcake** [emberjs/ember-test-helpers#727]
When ember is served it advises `DEPRECATION: ember-cli-htmlbars-inline-precompile is no longer needed with ember-cli-htmlbars versions 4.0.0 and higher, please remove it from `/Users/jess/ember-quickstart/package.json``

NOTE: I also raise this in ember-cli as [issue 8895](https://github.com/ember-cli/ember-cli/issues/8895)

I looked here in `ember-test-helpers`, and `htmlbars-inline-precompile` is not in the package.json, but it is in the yarn.lock file?

```
> npm ls ember-cli-htmlbars-inline-precompile                                                                                      [14:46:46]
ember-quickstart@0.0.0 /Users/jess/ember-quickstart
├── ember-cli-htmlbars-inline-precompile@3.0.1 
└─┬ ember-qunit@4.5.1
  └─┬ @ember/test-helpers@1.6.1
    └── ember-cli-htmlbars-inline-precompile@2.1.0 
```

**Comment by rwjblue** [comment]
This library doesn't trigger the deprecation (it uses an older version of ember-cli-htmlbars due to requiring Node 6 support still). 

I'm going to go ahead and close this for now, but we will absolutely be updating to the latest version once we drop Node 6.
