### ISSUE TITLE
Action logging mode

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember-test-helpers#740]
When debugging tests it can often be useful to `console.log()` before/after e.g. an `await click()` to know when things are breaking or what action might be causing a deprecation message.

I would like to propose an "action logging mode", where each of our built-in actions uses a `console.log()` if a certain query parameter is set on the testing page. This could be coupled with a custom QUnit option, that would appear as a checkbox in the QUnit UI.

/cc @rwjblue

**Comment by ro0gr** [comment]
just a weird thought: we can maybe even integrate with ember-inspector. That can avoid polluting the console and might provide some future interactive enhancements for the actions log.

**Comment by rwjblue** [comment]
> I would like to propose an "action logging mode", where each of our built-in actions uses a console.log()

The word "actions" here is confusing me. Do you mean, each of our internal utility functions? Each event that is fired? Something else?

**Comment by Turbo87** [comment]
> The word "actions" here is confusing me. Do you mean, each of our internal utility functions?

not necessarily the *internal* functions, but at least the publicly exported ones like `click()` and `fillIn()`.

> Each event that is fired?

that is an interesting idea. I've mostly thought about the high-level helpers, but the individual events might also make sense. maybe use `console.groupCollapsed()` for the high-level helpers and then `console.log()` for the events? 🤔

**Comment by rwjblue** [comment]
Ya, seems reasonable to me.
