### ISSUE TITLE
Deprecate `this.render` and `this.clearRender`

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-test-helpers#794]
These APIs were a complete accident: during a very early iteration of the new system I added these APIs, then subsequently replaced them with the utility style import APIs for the final design.

I just realized that these had not been deprecated yet 😩:facepalm: 

https://github.com/emberjs/ember-test-helpers/blob/a5f59e41bce78a66dbcd0f4dd7e82ff874c75594/addon-test-support/%40ember/test-helpers/setup-rendering-context.ts#L210-L223

**Comment by Mikek2252** [comment]
@rwjblue I can help with this, Could i get some info on what to put in the messages?

**Comment by rwjblue** [comment]
Thanks! Ya, the message basically would need to say that you should refactor from `this.render` to `render` imported from `@ember/test-helpers`.

**Comment by Mikek2252** [comment]
@rwjblue I guess this can be closed now?

**Comment by rwjblue** [comment]
Yep, thank you!
