### ISSUE TITLE
Generated controller test fails to lookup another controller factory (through needs)

### ISSUE THREAD

**Issue by balinterdi** [emberjs/ember-test-helpers#8]
I created a controller test through `ember generate controller-test band/songs` and added a dependency that the real controller under test has:

``` js
import {
  moduleFor,
  test
} from 'ember-qunit';

moduleFor('controller:band/songs', 'BandSongsController', {
  // Specify the other units that are required for this test.
  needs: ['controller:band']
});

// Replace this with your real tests.
test('it exists', function() {
  var controller = this.subject();
  ok(controller);
});
```

That is the only thing I changed. When I run the test I get the following error:

> Attempting to register an unknown factory: `controller:band`

I am running ember-cli 0.1.4, ember-qunit 0.1.8 (bower), ember-cli-qunit 0.1.2 (npm) and I checked that these are the latest versions from both. In fact, ember-cli-qunit installs the right version of ember-qunit in bower.

I also tried to manually set up the resolver by doing this in the test file:

``` js
import resolver from '../../../helpers/resolver';
setResolver(resolver);
```

This did not help, however.

**Comment by ahx** [comment]
I get this error, when trying to require a controller that is auto-generated by Ember while the application is running.
Adding files with empty controllers (`export default Ember.Controller.extend();`), worked around this issue for me.

However, I was depending on other controllers just to get their 'model' property, which feels wrong. So i changed my code to pass all required properties inside setupController of the associated route. Not sure what's best practice.

**Comment by jonnedeprez** [comment]
Any progress on this one? It's an old issue, but I'm still bumping into it (Ember 2.12.2). It's a bit odd to have to create empty controllers just to make tests succeed.

**Comment by rwjblue** [comment]
This should be addressed when using the new testing APIs provided by ember-qunit.

Closing....
