### ISSUE TITLE
How can I use helpers on shadow dom elements ?

### ISSUE THREAD

**Issue by Arijit-Roy** [emberjs/ember-test-helpers#841]
We are using polymer written web components in our project.  They come with their own shadow dom. 

I am trying to write a test case where in I need to access an input element in the shadow dom of a web component.  Then click on it and trigger a key event after that.  Like below. 
```
let input = document
      .querySelector('web-component')
      .shadowRoot.querySelector('input');
 // works
 await click(input);
 // does not work
 await triggerKeyEvent(input, 'keydown', 37);
 // works but does not fire change/keyup event on the web component
 await fillIn(input, '11/11/201');
```
Is there anything that I can do differently to make this work ? Thanks in advance !

**Comment by rwjblue** [comment]
Can you make a small reproduction that we could use to see what is going on?
