### ISSUE TITLE
triggerKeyEvent is not IE11 compatible due to Array.find

### ISSUE THREAD

**Issue by raido** [emberjs/ember-test-helpers#871]
`Array.find` usage in `triggerKeyEvent` method breaks it for IE11.

Reference: https://github.com/emberjs/ember-test-helpers/blob/a6af003242f04653fac31df8f93a55bfb57ac830/addon-test-support/%40ember/test-helpers/dom/trigger-key-event.ts#L109

Current workaround is to include `Array.find` polyfill for tests only if application itself does not depend on it.

`app.import("vendor/array-find-polyfill.js", { type: "test" });`

**Comment by rwjblue** [comment]
Eeck! Sorry about that @raido!

We should definitely fix, would love a PR if someone has the time.

**Comment by raido** [comment]
This should be closed, PR is merged.
