### ISSUE TITLE
find() considered a global and not picked up by eslint

### ISSUE THREAD

**Issue by mydea** [emberjs/ember-test-helpers#882]
I am not 100% sure if this is caused by this repo, but I ran into this a couple of times now - somehow, `find()` is not picked up by eslint's no-undef rule. So this code:

```js
import { module, test } from 'qunit';

module('find is considered a global', function () {
  test('find should not be a global', async function (assert) {
    let body = find('body');

    assert.ok(body && body.tagName === 'BODY');
  });
});
```

will pass eslint just fine, while replacing `find()` with e.g. `findAll()` will correctly error. I have made a reproduction in this repository here: https://github.com/mydea/ember-test-helpers/tree/find-considered-global, if you check this out and run `yarn lint` it will pass, even though there is this: https://github.com/mydea/ember-test-helpers/blob/find-considered-global/tests/integration/find-not-linted-test.js

I have tried to dug a bit where this could come from but haven't been successful in finding anything, so maybe somebody here has an idea :) It happened to me a few times now, that I added or copied a block using `find()` in a test, without importing it, and not noticing it until the tests run and fail due to it.

**Comment by rwjblue** [comment]
It is an allowed browser global property (not related to `@ember/test-helpers`):

https://developer.mozilla.org/en-US/docs/Web/API/Window/find

😭 😭 😭
