### ISSUE TITLE
`input[type=file].value = ''` does not reset `input.files` after triggerEvent

### ISSUE THREAD

**Issue by nag5000** [emberjs/ember-test-helpers#920]
```js
const file = new File(['(⌐□_□)'], 'chucknorris.png', { type: 'image/png' });
await triggerEvent(fileInput, 'change', { files: [file] });
fileInput.files.length; // 1
fileInput.value = '';
fileInput.files.length; // Actual: 1, Expected: 0.
```

Tmp workaround:
```js
const fileInputProto = Object.getPrototypeOf(fileInput);
const inputValueProp = Object.getOwnPropertyDescriptor(fileInputProto, 'value');
Object.defineProperty(fileInput, 'value', {
  configurable: true,
  get() {
    return inputValueProp.get.call(fileInput);
  },
  set(value) {
    inputValueProp.set.call(fileInput, value);

    Object.defineProperty(fileInput, 'files', {
      configurable: true,
      value: []
    });
  }
});

```

**Comment by rwjblue** [comment]
Huh. Are you supposed to be able to truncate it by just assigning value like that? I'm not opposed to the a PR adding the work around _IFF_ that is a normal usage pattern for folks.

**Comment by nag5000** [comment]
It's by spec: https://html.spec.whatwg.org/multipage/input.html#dom-input-value-filename
> On setting, if the new value is the empty string, empty the list of selected files; otherwise, throw an "InvalidStateError" DOMException.

And it's the most popular way to reset `input[type=file]` on stackoverflow ;)

**Comment by rwjblue** [comment]
Thank you! Sorry for not knowing, I just haven't used `Files` very much personally...

**Comment by rwjblue** [comment]
In order to fix, we need to:

* add a failing test case (seems _basically_ to be exactly what you have written above)
* Add the work around that you mention here

https://github.com/emberjs/ember-test-helpers/blob/e1cb9b462016c3df0c88e92afaa560f6daaf683f/addon-test-support/%40ember/test-helpers/dom/fire-event.ts#L260-L270
