### ISSUE TITLE
Installation section is incorrect / select helper is not available / 2.0 seems to be incompatible with qunit

### ISSUE THREAD

**Issue by st-h** [emberjs/ember-test-helpers#942]
I was trying to use the `select` helper with a pretty much up-to-date app. However, the import statement `import { select } from '@ember/test-helpers';` leads to the error `select is not exported`.

The installation section suggests that only recent ember-quint is needed. My package.json has current `"ember-qunit": "^4.6.0"`. Checking the lock file, however shows that ember test helpers < 2 is installed, which seems to not (yet) export the select helper.

I tried to add `"@ember/test-helpers": "^2.0.1"` to my package.json. And then the error changes to: `TypeError: (0 , _testHelpers.select) is not a function` while vstudio still complains that select is not exported.

So, I tried to add `"@ember/test-helpers": "2.0.1"` to the `resolutions` section of the package.json. Now this changes the error message to: 
```
loader.js:247 Uncaught Error: Could not find module `ember-test-helpers` imported from `ember-qunit/legacy-2-x/module-for`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at tests-suffix.js:1
```
I suspect this pretty much tells that ember-qunit is incompatible with the 2.x release of test helpers?

How do I use the select helper?

**Comment by rwjblue** [comment]
ember-cli@3.23.0 will contain the new releases of ember-qunit and @ember/test-helpers, the migration info is [in this document](https://github.com/emberjs/ember-qunit/blob/master/docs/migration.md).

**Comment by st-h** [comment]
@rwjblue Awesome. Thanks for the explanation.
