### ISSUE TITLE
Helpers no longer work properly with scheduled run-loop queues in v2

### ISSUE THREAD

**Issue by drewlee** [emberjs/ember-test-helpers#947]
Test helpers, particularly `render`, seem to be out of sync with scheduled run-loop timers. This causes integration and acceptance tests to fail when a component schedules work on a queue (e.g., `afterRender`).

I've create a simple use case to demonstrate the issue. It consists of a basic component that schedules programmatic focus placement on an `afterRender` queue. It is very similar to some of the test failures I've noticed within our applications after upgrading to v2: https://github.com/drewlee/helpers-async.

[There are two tests for the component.](https://github.com/drewlee/helpers-async/blob/master/tests/integration/components/basic-search-test.js) The first demonstrates the regression. What's particularly interesting is that running `getSettledState()` after `render`/`click` shows that the app still consists of pending timers and run-loop. The second test shows that a test can be coerced into passing by adding a `settled` waiter immediately after calling `render`. However, the app is still not quite settled after `click` resolves, so this seems to be symptomatic of all test helpers.

<img width="1392" alt="Screen Shot 2020-11-24 at 12 41 12 AM" src="https://user-images.githubusercontent.com/945868/100069590-ca550280-2ded-11eb-9f14-d605152a7618.png">

I'm not exactly too sure whether the test helpers resolve prematurely before the run-loop stuff is complete, or whether the test helpers somehow trigger a new run loop. Especially given that the component's behavior is altered because the scheduled `focus` call ends up executing before the input is rendered (hence the `Cannot read property 'focus' of null` exception).

What I did find, is that removing this [noop then callback in helper-hooks.js](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/-internal/helper-hooks.ts#L64) resolves the issue. I'm fairly certain that it's there for a good reason, so I'm somewhat hesitant for suggesting its removal as this may be a symptom of an issue related to Ember source, Backburner, or even RSVP. It seems very enigmatic for the stuff we're trying to avoid in this [RSVP config](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/-utils.ts#L55) though.

**Comment by drewlee** [comment]
@scalvert this is the bug that I've been trying to pin down for a while. I've finally traced it down to the fact that all of the test failures were from components that schedule stuff on a run-loop queue.

**Comment by scalvert** [comment]
@drewlee thanks for chasing this down. This is very odd behavior, and I wonder whether this further changed when we imported and used the `_Promise` util (which change to using an RSVP promise). I ask because the behavior is slightly different between [RSVP's `then`](https://github.com/tildeio/rsvp.js/blob/master/lib/rsvp/then.js#L32) vs. native `then`. That said, I do believe there's a subtle problem here that we need to dig into, and isn't immediately jumping out at me.

@rwjblue thoughts?

**Comment by rwjblue** [comment]
I think we've root caused what is going on here (@stefanpenner, @scalvert, and myself). I should have a PR up soon with an explanation.

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember-test-helpers/pull/956 is a failing test PR for the underlying issue, with a detailed explanation of what is going on. Working on the fixes now.
