### ISSUE TITLE
Using dynamic import in FastBoot is broken with @ember/test-helpers#2

### ISSUE THREAD

**Issue by bobisjan** [emberjs/ember-test-helpers#985]
Hi 👋,

when upgrading to the latest `@ember/test-helpers#2` (with `ember-qunit`) the error `ReferenceError: document is not defined` starts to show up in FastBoot.

I'm not sure where does issue come from, the previous version of this add-on works fine, but I've made a simple repository to demonstrate the issue https://github.com/bobisjan/--ember-document-error/commit/67dceffc37f81524ddedea40c647c49cbb54a42a.

**Comment by bobisjan** [comment]
It seems to be fixed in the latest release `2.2.1` by #992 🎉.

**Comment by rwjblue** [comment]
Awesome, thank you for checking @bobisjan!
