### ISSUE TITLE
Using @ember/destroyable in teardownContext causes incompatibility with ember-mocha

### ISSUE THREAD

**Issue by yads** [emberjs/ember-test-helpers#986]
teardownContext causes ember-mocha tests to fail with:

> Error: Attempted to register a destructor with an object that is already destroying or destroyed

It seems like Mocha potentially reuses contexts from test to test, so the Ember destroyable module thinks that a subsequent context is destroyed when it isn't considered destroyed by mocha or ember-mocha. This causes any tests after the first to fail at line:
https://github.com/emberjs/ember-test-helpers/blob/f2ebea61ad82e19486db5af35d8818d8cbe78f6a/addon-test-support/%40ember/test-helpers/setup-context.ts#L206

This is impacting [this PR](https://github.com/emberjs/ember-mocha/pull/631) in ember-mocha to uplift it to the latest version of ember-test-helpers. Only calling teardownContext on `this.owner` works fine in Ember 3.20, but fails in earlier versions.

**Comment by yads** [comment]
I've figured out how to get around this by using a Proxy object as a temporary context

**Comment by rwjblue** [comment]
Ya, the proxy solution seems good (to prevent shared mutation of the same context over and over again). Though, I think it would still be best if we add an option to disable destroying the test context.

**Comment by yads** [comment]
@rwjblue while I have you here, can you take a look at this PR https://github.com/emberjs/ember-mocha/pull/631 that I linked above? We're currently maintaining a fork of ember-mocha because it seems like the project doesn't have any maintainers. I'd love to get that merged in and perhaps take over maintenance of the project?

**Comment by rwjblue** [comment]
@yads - Can you make a new meta issue over there in ember-mocha so we can discuss the overall path forward? There are quite a few different open PRs and it isn't clear what the order of merging would be (or what is left to do, etc).

**Comment by yads** [comment]
@rwjblue done, see https://github.com/emberjs/ember-mocha/issues/638
